// Code generated by "stringer -type=AiJob"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AiJob_Guard-0]
	_ = x[AiJob_Patrol-1]
	_ = x[AiJob_GuardForce-2]
	_ = x[AiJob_Encounter-3]
	_ = x[AiJob_ProducedFighter-4]
	_ = x[AiJob_Convoy-5]
	_ = x[AiJob_Convoy_Defending-6]
	_ = x[AiJob_Border_Travelling-7]
	_ = x[AiJob_Value_8_Len_15-8]
	_ = x[AiJob_Value_9_Len_16-9]
	_ = x[AiJob_Count-10]
	_ = x[AiJob_Any-11]
}

const _AiJob_name = "AiJob_GuardAiJob_PatrolAiJob_GuardForceAiJob_EncounterAiJob_ProducedFighterAiJob_ConvoyAiJob_Convoy_DefendingAiJob_Border_TravellingAiJob_Value_8_Len_15AiJob_Value_9_Len_16AiJob_CountAiJob_Any"

var _AiJob_index = [...]uint8{0, 11, 23, 39, 54, 75, 87, 109, 132, 152, 172, 183, 192}

func (i AiJob) String() string {
	if i >= AiJob(len(_AiJob_index)-1) {
		return "AiJob(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AiJob_name[_AiJob_index[i]:_AiJob_index[i+1]]
}
