// Code generated by "stringer -type=AllowLocationMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllowLocationMode_All-0]
	_ = x[AllowLocationMode_SmallOnly-1]
	_ = x[AllowLocationMode_None-2]
}

const _AllowLocationMode_name = "AllowLocationMode_AllAllowLocationMode_SmallOnlyAllowLocationMode_None"

var _AllowLocationMode_index = [...]uint8{0, 21, 48, 70}

func (i AllowLocationMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AllowLocationMode_index)-1 {
		return "AllowLocationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AllowLocationMode_name[_AllowLocationMode_index[idx]:_AllowLocationMode_index[idx+1]]
}
