// Code generated by "stringer -type=BackpackWwiseIndex"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BackpackWwiseIndex_None-0]
	_ = x[BackpackWwiseIndex_Ammo-1]
	_ = x[BackpackWwiseIndex_AutomaticCannon-2]
	_ = x[BackpackWwiseIndex_SmallBallisticShield-3]
	_ = x[BackpackWwiseIndex_BallisticShield-4]
	_ = x[BackpackWwiseIndex_Displacement-5]
	_ = x[BackpackWwiseIndex_DroneMg-6]
	_ = x[BackpackWwiseIndex_EnergyShield-7]
	_ = x[BackpackWwiseIndex_Jumppack-8]
	_ = x[BackpackWwiseIndex_Medic-9]
	_ = x[BackpackWwiseIndex_RecoillessRifle-10]
	_ = x[BackpackWwiseIndex_Spear-11]
	_ = x[BackpackWwiseIndex_Support-12]
	_ = x[BackpackWwiseIndex_Chemicals-13]
	_ = x[BackpackWwiseIndex_Larva-14]
}

const _BackpackWwiseIndex_name = "BackpackWwiseIndex_NoneBackpackWwiseIndex_AmmoBackpackWwiseIndex_AutomaticCannonBackpackWwiseIndex_SmallBallisticShieldBackpackWwiseIndex_BallisticShieldBackpackWwiseIndex_DisplacementBackpackWwiseIndex_DroneMgBackpackWwiseIndex_EnergyShieldBackpackWwiseIndex_JumppackBackpackWwiseIndex_MedicBackpackWwiseIndex_RecoillessRifleBackpackWwiseIndex_SpearBackpackWwiseIndex_SupportBackpackWwiseIndex_ChemicalsBackpackWwiseIndex_Larva"

var _BackpackWwiseIndex_index = [...]uint16{0, 23, 46, 80, 119, 153, 184, 210, 241, 268, 292, 326, 350, 376, 404, 428}

func (i BackpackWwiseIndex) String() string {
	if i < 0 || i >= BackpackWwiseIndex(len(_BackpackWwiseIndex_index)-1) {
		return "BackpackWwiseIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BackpackWwiseIndex_name[_BackpackWwiseIndex_index[i]:_BackpackWwiseIndex_index[i+1]]
}
