// Code generated by "stringer -type=BanterEventType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BanterEventType_None-0]
	_ = x[BanterEventType_IdleOnMission-1]
	_ = x[BanterEventType_IdleOnShip-2]
	_ = x[BanterEventType_IdleYawn-3]
	_ = x[BanterEventType_MissionStartReady-4]
	_ = x[BanterEventType_ExtractionWaiting-5]
	_ = x[BanterEventType_MissionNearbyHelldiver-6]
	_ = x[BanterEventType_ShipNearbyHelldiver-7]
	_ = x[BanterEventType_InLoadoutHellpod-8]
	_ = x[BanterEventType_Customization-9]
	_ = x[BanterEventType_MeetNewHelldiver-10]
	_ = x[BanterEventType_ApproachExtraction-11]
	_ = x[BanterEventType_WaitingForObjective-12]
	_ = x[BanterEventType_ObjectiveComplete-13]
	_ = x[BanterEventType_ApproachObjective-14]
	_ = x[BanterEventType_LocationCarnage-15]
	_ = x[BanterEventType_Count-16]
}

const _BanterEventType_name = "BanterEventType_NoneBanterEventType_IdleOnMissionBanterEventType_IdleOnShipBanterEventType_IdleYawnBanterEventType_MissionStartReadyBanterEventType_ExtractionWaitingBanterEventType_MissionNearbyHelldiverBanterEventType_ShipNearbyHelldiverBanterEventType_InLoadoutHellpodBanterEventType_CustomizationBanterEventType_MeetNewHelldiverBanterEventType_ApproachExtractionBanterEventType_WaitingForObjectiveBanterEventType_ObjectiveCompleteBanterEventType_ApproachObjectiveBanterEventType_LocationCarnageBanterEventType_Count"

var _BanterEventType_index = [...]uint16{0, 20, 49, 75, 99, 132, 165, 203, 238, 270, 299, 331, 365, 400, 433, 466, 497, 518}

func (i BanterEventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BanterEventType_index)-1 {
		return "BanterEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BanterEventType_name[_BanterEventType_index[idx]:_BanterEventType_index[idx+1]]
}
