// Code generated by "stringer -type=CityPlacementHeuristic"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CityPlacementHeuristic_Value_0_Len_46-0]
	_ = x[CityPlacementHeuristic_Value_1_Len_44-1]
	_ = x[CityPlacementHeuristic_Value_2_Len_39-2]
	_ = x[CityPlacementHeuristic_Value_3_Len_49-3]
	_ = x[CityPlacementHeuristic_Value_4_Len_50-4]
	_ = x[CityPlacementHeuristic_Value_5_Len_41-5]
	_ = x[CityPlacementHeuristic_Count-6]
}

const _CityPlacementHeuristic_name = "CityPlacementHeuristic_Value_0_Len_46CityPlacementHeuristic_Value_1_Len_44CityPlacementHeuristic_Value_2_Len_39CityPlacementHeuristic_Value_3_Len_49CityPlacementHeuristic_Value_4_Len_50CityPlacementHeuristic_Value_5_Len_41CityPlacementHeuristic_Count"

var _CityPlacementHeuristic_index = [...]uint8{0, 37, 74, 111, 148, 185, 222, 250}

func (i CityPlacementHeuristic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CityPlacementHeuristic_index)-1 {
		return "CityPlacementHeuristic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CityPlacementHeuristic_name[_CityPlacementHeuristic_index[idx]:_CityPlacementHeuristic_index[idx+1]]
}
