// Code generated by "stringer -type=CrosshairWeaponType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CrosshairWeaponType_Default-0]
	_ = x[CrosshairWeaponType_CrosshairNever-1]
	_ = x[CrosshairWeaponType_CrosshairAlways-2]
	_ = x[CrosshairWeaponType_AssaultRifle-3]
	_ = x[CrosshairWeaponType_PumpShotgun-4]
	_ = x[CrosshairWeaponType_AutoShotgun-5]
	_ = x[CrosshairWeaponType_Pistol-6]
	_ = x[CrosshairWeaponType_Revolver-7]
	_ = x[CrosshairWeaponType_Laser-8]
	_ = x[CrosshairWeaponType_LaserCannon-9]
	_ = x[CrosshairWeaponType_LaserPulseCannon-10]
	_ = x[CrosshairWeaponType_Railgun-11]
	_ = x[CrosshairWeaponType_Javelin-12]
	_ = x[CrosshairWeaponType_Throwable-13]
	_ = x[CrosshairWeaponType_Physgun-14]
	_ = x[CrosshairWeaponType_Value_15-15]
	_ = x[CrosshairWeaponType_Value_16-16]
	_ = x[CrosshairWeaponType_Value_17-17]
	_ = x[CrosshairWeaponType_Value_18-18]
	_ = x[CrosshairWeaponType_None-19]
	_ = x[CrosshairWeaponType_Count-20]
}

const _CrosshairWeaponType_name = "CrosshairWeaponType_DefaultCrosshairWeaponType_CrosshairNeverCrosshairWeaponType_CrosshairAlwaysCrosshairWeaponType_AssaultRifleCrosshairWeaponType_PumpShotgunCrosshairWeaponType_AutoShotgunCrosshairWeaponType_PistolCrosshairWeaponType_RevolverCrosshairWeaponType_LaserCrosshairWeaponType_LaserCannonCrosshairWeaponType_LaserPulseCannonCrosshairWeaponType_RailgunCrosshairWeaponType_JavelinCrosshairWeaponType_ThrowableCrosshairWeaponType_PhysgunCrosshairWeaponType_Value_15CrosshairWeaponType_Value_16CrosshairWeaponType_Value_17CrosshairWeaponType_Value_18CrosshairWeaponType_NoneCrosshairWeaponType_Count"

var _CrosshairWeaponType_index = [...]uint16{0, 27, 61, 96, 128, 159, 190, 216, 244, 269, 300, 336, 363, 390, 419, 446, 474, 502, 530, 558, 582, 607}

func (i CrosshairWeaponType) String() string {
	if i >= CrosshairWeaponType(len(_CrosshairWeaponType_index)-1) {
		return "CrosshairWeaponType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CrosshairWeaponType_name[_CrosshairWeaponType_index[i]:_CrosshairWeaponType_index[i+1]]
}
