// Code generated by "stringer -type=DamageMultiplier"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DamageMultiplier_None-0]
	_ = x[DamageMultiplier_Critical-1]
	_ = x[DamageMultiplier_Normal-2]
	_ = x[DamageMultiplier_Reduced-3]
	_ = x[DamageMultiplier_Symbolic-4]
}

const _DamageMultiplier_name = "DamageMultiplier_NoneDamageMultiplier_CriticalDamageMultiplier_NormalDamageMultiplier_ReducedDamageMultiplier_Symbolic"

var _DamageMultiplier_index = [...]uint8{0, 21, 46, 69, 93, 118}

func (i DamageMultiplier) String() string {
	if i >= DamageMultiplier(len(_DamageMultiplier_index)-1) {
		return "DamageMultiplier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DamageMultiplier_name[_DamageMultiplier_index[i]:_DamageMultiplier_index[i+1]]
}
