// Code generated by "stringer -type=DangerLevel"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DangerLevel_None-0]
	_ = x[DangerLevel_Projectile-1]
	_ = x[DangerLevel_Melee-2]
	_ = x[DangerLevel_Explosion-3]
	_ = x[DangerLevel_Damage-4]
	_ = x[DangerLevel_Beam-5]
	_ = x[DangerLevel_Grenade-6]
	_ = x[DangerLevel_Impact-7]
	_ = x[DangerLevel_Value_8_Len_15-8]
	_ = x[DangerLevel_Count-9]
}

const _DangerLevel_name = "DangerLevel_NoneDangerLevel_ProjectileDangerLevel_MeleeDangerLevel_ExplosionDangerLevel_DamageDangerLevel_BeamDangerLevel_GrenadeDangerLevel_ImpactDangerLevel_Value_8_Len_15DangerLevel_Count"

var _DangerLevel_index = [...]uint8{0, 16, 38, 55, 76, 94, 110, 129, 147, 173, 190}

func (i DangerLevel) String() string {
	if i >= DangerLevel(len(_DangerLevel_index)-1) {
		return "DangerLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DangerLevel_name[_DangerLevel_index[i]:_DangerLevel_index[i+1]]
}
