// Code generated by "stringer -type=DangerWarningType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DangerWarningType_None-0]
	_ = x[DangerWarningType_EnemyOrbital-1]
	_ = x[DangerWarningType_EnemyAA-2]
	_ = x[DangerWarningType_IonStorm-3]
	_ = x[DangerWarningType_IntenseHeat-4]
	_ = x[DangerWarningType_ExtremeCold-5]
	_ = x[DangerWarningType_Earthquake-6]
	_ = x[DangerWarningType_MeteorShower-7]
	_ = x[DangerWarningType_VolcanicActivity-8]
	_ = x[DangerWarningType_FireTornado-9]
	_ = x[DangerWarningType_Value_10_Len_27-10]
	_ = x[DangerWarningType_Value_11_Len_27-11]
	_ = x[DangerWarningType_Value_12_Len_27-12]
	_ = x[DangerWarningType_Value_13_Len_26-13]
	_ = x[DangerWarningType_Value_14_Len_28-14]
	_ = x[DangerWarningType_StratagemBlocker-15]
	_ = x[DangerWarningType_Value_16_Len_36-16]
	_ = x[DangerWarningType_Modifier_StratagemSlowCallIn-17]
	_ = x[DangerWarningType_Modifier_StratagemLongerCooldown-18]
	_ = x[DangerWarningType_Modifier_StratagemOrbitalAccuracy-19]
	_ = x[DangerWarningType_Modifier_MissionTimerReduced-20]
	_ = x[DangerWarningType_Modifier_HiddenObjectives-21]
	_ = x[DangerWarningType_Modifier_SporeBlackout-22]
	_ = x[DangerWarningType_Modifier_FogGenerator-23]
	_ = x[DangerWarningType_Modifier_StratagemLoadoutCount-24]
	_ = x[DangerWarningType_Value_25_Len_42-25]
	_ = x[DangerWarningType_Value_26_Len_42-26]
	_ = x[DangerWarningType_Value_27_Len_39-27]
	_ = x[DangerWarningType_Value_28_Len_47-28]
	_ = x[DangerWarningType_Value_29_Len_32-29]
	_ = x[DangerWarningType_Value_30_Len_40-30]
	_ = x[DangerWarningType_Value_31_Len_46-31]
	_ = x[DangerWarningType_Value_32_Len_42-32]
	_ = x[DangerWarningType_Count-33]
}

const _DangerWarningType_name = "DangerWarningType_NoneDangerWarningType_EnemyOrbitalDangerWarningType_EnemyAADangerWarningType_IonStormDangerWarningType_IntenseHeatDangerWarningType_ExtremeColdDangerWarningType_EarthquakeDangerWarningType_MeteorShowerDangerWarningType_VolcanicActivityDangerWarningType_FireTornadoDangerWarningType_Value_10_Len_27DangerWarningType_Value_11_Len_27DangerWarningType_Value_12_Len_27DangerWarningType_Value_13_Len_26DangerWarningType_Value_14_Len_28DangerWarningType_StratagemBlockerDangerWarningType_Value_16_Len_36DangerWarningType_Modifier_StratagemSlowCallInDangerWarningType_Modifier_StratagemLongerCooldownDangerWarningType_Modifier_StratagemOrbitalAccuracyDangerWarningType_Modifier_MissionTimerReducedDangerWarningType_Modifier_HiddenObjectivesDangerWarningType_Modifier_SporeBlackoutDangerWarningType_Modifier_FogGeneratorDangerWarningType_Modifier_StratagemLoadoutCountDangerWarningType_Value_25_Len_42DangerWarningType_Value_26_Len_42DangerWarningType_Value_27_Len_39DangerWarningType_Value_28_Len_47DangerWarningType_Value_29_Len_32DangerWarningType_Value_30_Len_40DangerWarningType_Value_31_Len_46DangerWarningType_Value_32_Len_42DangerWarningType_Count"

var _DangerWarningType_index = [...]uint16{0, 22, 52, 77, 103, 132, 161, 189, 219, 253, 282, 315, 348, 381, 414, 447, 481, 514, 560, 610, 661, 707, 750, 790, 829, 877, 910, 943, 976, 1009, 1042, 1075, 1108, 1141, 1164}

func (i DangerWarningType) String() string {
	if i >= DangerWarningType(len(_DangerWarningType_index)-1) {
		return "DangerWarningType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DangerWarningType_name[_DangerWarningType_index[i]:_DangerWarningType_index[i+1]]
}
