// Code generated by "stringer -type=DeathPropagation"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeathPropagation_None-0]
	_ = x[DeathPropagation_ToParent-1]
	_ = x[DeathPropagation_ToChildren-2]
	_ = x[DeathPropagation_Both-3]
}

const _DeathPropagation_name = "DeathPropagation_NoneDeathPropagation_ToParentDeathPropagation_ToChildrenDeathPropagation_Both"

var _DeathPropagation_index = [...]uint8{0, 21, 46, 73, 94}

func (i DeathPropagation) String() string {
	if i >= DeathPropagation(len(_DeathPropagation_index)-1) {
		return "DeathPropagation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeathPropagation_name[_DeathPropagation_index[i]:_DeathPropagation_index[i+1]]
}
