// Code generated by "stringer -type=DeathDecayMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeathDecayMode_None-0]
	_ = x[DeathDecayMode_Regular-1]
	_ = x[DeathDecayMode_Long-2]
	_ = x[DeathDecayMode_Instant-3]
}

const _DeathDecayMode_name = "DeathDecayMode_NoneDeathDecayMode_RegularDeathDecayMode_LongDeathDecayMode_Instant"

var _DeathDecayMode_index = [...]uint8{0, 19, 41, 60, 82}

func (i DeathDecayMode) String() string {
	if i >= DeathDecayMode(len(_DeathDecayMode_index)-1) {
		return "DeathDecayMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeathDecayMode_name[_DeathDecayMode_index[i]:_DeathDecayMode_index[i+1]]
}
