// Code generated by "stringer -type=DepositRefill"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DepositRefill_None-0]
	_ = x[DepositRefill_Ammo-1]
	_ = x[DepositRefill_Medic-2]
	_ = x[DepositRefill_Supplies-3]
	_ = x[DepositRefill_Count-4]
}

const _DepositRefill_name = "DepositRefill_NoneDepositRefill_AmmoDepositRefill_MedicDepositRefill_SuppliesDepositRefill_Count"

var _DepositRefill_index = [...]uint8{0, 18, 36, 55, 77, 96}

func (i DepositRefill) String() string {
	if i >= DepositRefill(len(_DepositRefill_index)-1) {
		return "DepositRefill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DepositRefill_name[_DepositRefill_index[i]:_DepositRefill_index[i+1]]
}
