// Code generated by "stringer -type=EffectType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EffectType_None-0]
	_ = x[EffectType_Wet-1]
	_ = x[EffectType_Dry-2]
	_ = x[EffectType_Hot-3]
	_ = x[EffectType_Cold-4]
	_ = x[EffectType_BlownLeaves-5]
}

const _EffectType_name = "EffectType_NoneEffectType_WetEffectType_DryEffectType_HotEffectType_ColdEffectType_BlownLeaves"

var _EffectType_index = [...]uint8{0, 15, 29, 43, 57, 72, 94}

func (i EffectType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EffectType_index)-1 {
		return "EffectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EffectType_name[_EffectType_index[idx]:_EffectType_index[idx+1]]
}
