// Code generated by "stringer -type=ElementType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElementType_None-0]
	_ = x[ElementType_Fire-1]
	_ = x[ElementType_Electricity-2]
	_ = x[ElementType_Acid-3]
	_ = x[ElementType_Bleed-4]
	_ = x[ElementType_Gas-5]
	_ = x[ElementType_Value_6_Len_14-6]
	_ = x[ElementType_Count-7]
}

const _ElementType_name = "ElementType_NoneElementType_FireElementType_ElectricityElementType_AcidElementType_BleedElementType_GasElementType_Value_6_Len_14ElementType_Count"

var _ElementType_index = [...]uint8{0, 16, 32, 55, 71, 88, 103, 129, 146}

func (i ElementType) String() string {
	if i >= ElementType(len(_ElementType_index)-1) {
		return "ElementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElementType_name[_ElementType_index[i]:_ElementType_index[i+1]]
}
