// Code generated by "stringer -type=EnemyTag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnemyTag_None-0]
	_ = x[EnemyTag_BugAcid-1]
	_ = x[EnemyTag_BugArmored-2]
	_ = x[EnemyTag_BugPredators-3]
	_ = x[EnemyTag_BugFlyers-4]
	_ = x[EnemyTag_BugFodder-5]
	_ = x[EnemyTag_BugCrawlers-6]
	_ = x[EnemyTag_BugBalanced-7]
	_ = x[EnemyTag_Value_8_Len_29-8]
	_ = x[EnemyTag_Value_9_Len_20-9]
	_ = x[EnemyTag_Value_10_Len_24-10]
	_ = x[EnemyTag_Value_11_Len_30-11]
	_ = x[EnemyTag_Value_12_Len_32-12]
	_ = x[EnemyTag_BotAssault-13]
	_ = x[EnemyTag_BotPhalanx-14]
	_ = x[EnemyTag_BotArtillery-15]
	_ = x[EnemyTag_BotAir-16]
	_ = x[EnemyTag_BotPanzer-17]
	_ = x[EnemyTag_BotBalanced-18]
	_ = x[EnemyTag_Value_19_Len_22-19]
	_ = x[EnemyTag_Value_20_Len_32-20]
	_ = x[EnemyTag_BotIvoryLegion-21]
	_ = x[EnemyTag_Value_22_Len_23-22]
	_ = x[EnemyTag_Value_23_Len_28-23]
	_ = x[EnemyTag_Value_24_Len_26-24]
	_ = x[EnemyTag_Value_25_Len_24-25]
	_ = x[EnemyTag_Value_26_Len_28-26]
	_ = x[EnemyTag_Value_27_Len_33-27]
	_ = x[EnemyTag_Value_28_Len_13-28]
	_ = x[EnemyTag_Count-29]
	_ = x[MAX_NUM_ENEMY_TAGS_PER_MISSION-3]
}

const _EnemyTag_name = "EnemyTag_NoneEnemyTag_BugAcidEnemyTag_BugArmoredEnemyTag_BugPredatorsEnemyTag_BugFlyersEnemyTag_BugFodderEnemyTag_BugCrawlersEnemyTag_BugBalancedEnemyTag_Value_8_Len_29EnemyTag_Value_9_Len_20EnemyTag_Value_10_Len_24EnemyTag_Value_11_Len_30EnemyTag_Value_12_Len_32EnemyTag_BotAssaultEnemyTag_BotPhalanxEnemyTag_BotArtilleryEnemyTag_BotAirEnemyTag_BotPanzerEnemyTag_BotBalancedEnemyTag_Value_19_Len_22EnemyTag_Value_20_Len_32EnemyTag_BotIvoryLegionEnemyTag_Value_22_Len_23EnemyTag_Value_23_Len_28EnemyTag_Value_24_Len_26EnemyTag_Value_25_Len_24EnemyTag_Value_26_Len_28EnemyTag_Value_27_Len_33EnemyTag_Value_28_Len_13EnemyTag_Count"

var _EnemyTag_index = [...]uint16{0, 13, 29, 48, 69, 87, 105, 125, 145, 168, 191, 215, 239, 263, 282, 301, 322, 337, 355, 375, 399, 423, 446, 470, 494, 518, 542, 566, 590, 614, 628}

func (i EnemyTag) String() string {
	if i >= EnemyTag(len(_EnemyTag_index)-1) {
		return "EnemyTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnemyTag_name[_EnemyTag_index[i]:_EnemyTag_index[i+1]]
}
