// Code generated by "stringer -type=EquipmentDropMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquipmentDropMode_Decay-0]
	_ = x[EquipmentDropMode_Infinite-1]
	_ = x[EquipmentDropMode_InfiniteIfNonEmpty-2]
}

const _EquipmentDropMode_name = "EquipmentDropMode_DecayEquipmentDropMode_InfiniteEquipmentDropMode_InfiniteIfNonEmpty"

var _EquipmentDropMode_index = [...]uint8{0, 23, 49, 85}

func (i EquipmentDropMode) String() string {
	if i >= EquipmentDropMode(len(_EquipmentDropMode_index)-1) {
		return "EquipmentDropMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EquipmentDropMode_name[_EquipmentDropMode_index[i]:_EquipmentDropMode_index[i+1]]
}
