// Code generated by "stringer -type=EquipmentWwiseIndex"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquipmentWwiseIndex_Carryable_FuelBarrel - -4]
	_ = x[EquipmentWwiseIndex_Carryable_Briefcase - -3]
	_ = x[EquipmentWwiseIndex_Carryable_Blackbox - -2]
	_ = x[EquipmentWwiseIndex_Carryable_Flag - -1]
	_ = x[EquipmentWwiseIndex_None-0]
	_ = x[EquipmentWwiseIndex_Primary_RifleSm-1]
	_ = x[EquipmentWwiseIndex_Primary_RifleBig-2]
	_ = x[EquipmentWwiseIndex_Primary_SMG-3]
	_ = x[EquipmentWwiseIndex_Primary_Energy-4]
	_ = x[EquipmentWwiseIndex_Primary_Shotgun-5]
	_ = x[EquipmentWwiseIndex_Sidearm_Pistol-6]
	_ = x[EquipmentWwiseIndex_Support_GrenadeLauncher-7]
	_ = x[EquipmentWwiseIndex_Support_RecoillessRifle-8]
	_ = x[EquipmentWwiseIndex_Support_MissileLauncher-9]
	_ = x[EquipmentWwiseIndex_Support_Machinegun-10]
	_ = x[EquipmentWwiseIndex_Support_Sniper-11]
	_ = x[EquipmentWwiseIndex_Support_Chemgun-12]
	_ = x[EquipmentWwiseIndex_Support_Arc_Thrower-13]
	_ = x[EquipmentWwiseIndex_Melee_Heavy-14]
	_ = x[EquipmentWwiseIndex_Melee_Light-15]
	_ = x[EquipmentWwiseIndex_Melee_Spear-16]
	_ = x[EquipmentWwiseIndex_Melee_Flag-17]
}

const _EquipmentWwiseIndex_name = "EquipmentWwiseIndex_Carryable_FuelBarrelEquipmentWwiseIndex_Carryable_BriefcaseEquipmentWwiseIndex_Carryable_BlackboxEquipmentWwiseIndex_Carryable_FlagEquipmentWwiseIndex_NoneEquipmentWwiseIndex_Primary_RifleSmEquipmentWwiseIndex_Primary_RifleBigEquipmentWwiseIndex_Primary_SMGEquipmentWwiseIndex_Primary_EnergyEquipmentWwiseIndex_Primary_ShotgunEquipmentWwiseIndex_Sidearm_PistolEquipmentWwiseIndex_Support_GrenadeLauncherEquipmentWwiseIndex_Support_RecoillessRifleEquipmentWwiseIndex_Support_MissileLauncherEquipmentWwiseIndex_Support_MachinegunEquipmentWwiseIndex_Support_SniperEquipmentWwiseIndex_Support_ChemgunEquipmentWwiseIndex_Support_Arc_ThrowerEquipmentWwiseIndex_Melee_HeavyEquipmentWwiseIndex_Melee_LightEquipmentWwiseIndex_Melee_SpearEquipmentWwiseIndex_Melee_Flag"

var _EquipmentWwiseIndex_index = [...]uint16{0, 40, 79, 117, 151, 175, 210, 246, 277, 311, 346, 380, 423, 466, 509, 547, 581, 616, 655, 686, 717, 748, 778}

func (i EquipmentWwiseIndex) String() string {
	i -= -4
	if i < 0 || i >= EquipmentWwiseIndex(len(_EquipmentWwiseIndex_index)-1) {
		return "EquipmentWwiseIndex(" + strconv.FormatInt(int64(i+-4), 10) + ")"
	}
	return _EquipmentWwiseIndex_name[_EquipmentWwiseIndex_index[i]:_EquipmentWwiseIndex_index[i+1]]
}
