// Code generated by "stringer -type=EquipmentType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquipmentType_All-0]
	_ = x[EquipmentType_AssaultRifle-1]
	_ = x[EquipmentType_MarksmanRifle-2]
	_ = x[EquipmentType_SniperRifle-3]
	_ = x[EquipmentType_SMG-4]
	_ = x[EquipmentType_MachineGun-5]
	_ = x[EquipmentType_Shotgun-6]
	_ = x[EquipmentType_Explosive-7]
	_ = x[EquipmentType_Energy-8]
	_ = x[EquipmentType_Incendiary-9]
	_ = x[EquipmentType_Pistol-10]
	_ = x[EquipmentType_Revolver-11]
	_ = x[EquipmentType_EnergySidearm-12]
	_ = x[EquipmentType_LauncherSidearm-13]
	_ = x[EquipmentType_StandardGrenade-14]
	_ = x[EquipmentType_SpecialGrenade-15]
	_ = x[EquipmentType_Backpack-16]
	_ = x[EquipmentType_BackpackSupport-17]
	_ = x[EquipmentType_BackpackJumppack-18]
	_ = x[EquipmentType_BackpackMedic-19]
	_ = x[EquipmentType_BackpackDrone-20]
	_ = x[EquipmentType_BackpackEnergyShield-21]
	_ = x[EquipmentType_BackpackSupply-22]
	_ = x[EquipmentType_BackpackDisplacement-23]
	_ = x[EquipmentType_BackpackShield-24]
	_ = x[EquipmentType_Value_25_Len_31-25]
	_ = x[EquipmentType_Value_26_Len_30-26]
	_ = x[EquipmentType_Objective-27]
	_ = x[EquipmentType_Value_28_Len_29-28]
	_ = x[EquipmentType_Melee-29]
	_ = x[EquipmentType_Value_30_Len_21-30]
	_ = x[EquipmentType_Hidden-31]
	_ = x[EquipmentType_Count-32]
}

const _EquipmentType_name = "EquipmentType_AllEquipmentType_AssaultRifleEquipmentType_MarksmanRifleEquipmentType_SniperRifleEquipmentType_SMGEquipmentType_MachineGunEquipmentType_ShotgunEquipmentType_ExplosiveEquipmentType_EnergyEquipmentType_IncendiaryEquipmentType_PistolEquipmentType_RevolverEquipmentType_EnergySidearmEquipmentType_LauncherSidearmEquipmentType_StandardGrenadeEquipmentType_SpecialGrenadeEquipmentType_BackpackEquipmentType_BackpackSupportEquipmentType_BackpackJumppackEquipmentType_BackpackMedicEquipmentType_BackpackDroneEquipmentType_BackpackEnergyShieldEquipmentType_BackpackSupplyEquipmentType_BackpackDisplacementEquipmentType_BackpackShieldEquipmentType_Value_25_Len_31EquipmentType_Value_26_Len_30EquipmentType_ObjectiveEquipmentType_Value_28_Len_29EquipmentType_MeleeEquipmentType_Value_30_Len_21EquipmentType_HiddenEquipmentType_Count"

var _EquipmentType_index = [...]uint16{0, 17, 43, 70, 95, 112, 136, 157, 180, 200, 224, 244, 266, 293, 322, 351, 379, 401, 430, 460, 487, 514, 548, 576, 610, 638, 667, 696, 719, 748, 767, 796, 816, 835}

func (i EquipmentType) String() string {
	if i >= EquipmentType(len(_EquipmentType_index)-1) {
		return "EquipmentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EquipmentType_name[_EquipmentType_index[i]:_EquipmentType_index[i+1]]
}
