// Code generated by "stringer -type=ExertionLevelIndex"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExertionLevelIndex_None-0]
	_ = x[ExertionLevelIndex_Inconsiderable-1]
	_ = x[ExertionLevelIndex_Low-2]
	_ = x[ExertionLevelIndex_Medium-3]
	_ = x[ExertionLevelIndex_High-4]
	_ = x[ExertionLevelIndex_Injured-5]
	_ = x[ExertionLevelIndex_Hemmorage-6]
	_ = x[ExertionLevelIndex_HemmorageCritical-7]
}

const _ExertionLevelIndex_name = "ExertionLevelIndex_NoneExertionLevelIndex_InconsiderableExertionLevelIndex_LowExertionLevelIndex_MediumExertionLevelIndex_HighExertionLevelIndex_InjuredExertionLevelIndex_HemmorageExertionLevelIndex_HemmorageCritical"

var _ExertionLevelIndex_index = [...]uint8{0, 23, 56, 78, 103, 126, 152, 180, 216}

func (i ExertionLevelIndex) String() string {
	if i >= ExertionLevelIndex(len(_ExertionLevelIndex_index)-1) {
		return "ExertionLevelIndex(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExertionLevelIndex_name[_ExertionLevelIndex_index[i]:_ExertionLevelIndex_index[i+1]]
}
