// Code generated by "stringer -type=ExplorationRewardType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExplorationRewardType_None-0]
	_ = x[ExplorationRewardType_exploration_requisition_slips-1]
	_ = x[ExplorationRewardType_exploration_medals-2]
	_ = x[ExplorationRewardType_exploration_credit_card-3]
	_ = x[ExplorationRewardType_Count-4]
}

const _ExplorationRewardType_name = "ExplorationRewardType_NoneExplorationRewardType_exploration_requisition_slipsExplorationRewardType_exploration_medalsExplorationRewardType_exploration_credit_cardExplorationRewardType_Count"

var _ExplorationRewardType_index = [...]uint8{0, 26, 77, 117, 162, 189}

func (i ExplorationRewardType) String() string {
	if i >= ExplorationRewardType(len(_ExplorationRewardType_index)-1) {
		return "ExplorationRewardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExplorationRewardType_name[_ExplorationRewardType_index[i]:_ExplorationRewardType_index[i+1]]
}
