// Code generated by "stringer -type=ExplosionVerificationMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExplosionVerificationMode_None-0]
	_ = x[ExplosionVerificationMode_OuterRadius-1]
	_ = x[ExplosionVerificationMode_All-2]
}

const _ExplosionVerificationMode_name = "ExplosionVerificationMode_NoneExplosionVerificationMode_OuterRadiusExplosionVerificationMode_All"

var _ExplosionVerificationMode_index = [...]uint8{0, 30, 67, 96}

func (i ExplosionVerificationMode) String() string {
	if i >= ExplosionVerificationMode(len(_ExplosionVerificationMode_index)-1) {
		return "ExplosionVerificationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExplosionVerificationMode_name[_ExplosionVerificationMode_index[i]:_ExplosionVerificationMode_index[i+1]]
}
