// Code generated by "stringer -type=ExplosiveMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExplosiveMode_Timed-0]
	_ = x[ExplosiveMode_Impact-1]
	_ = x[ExplosiveMode_External-2]
	_ = x[ExplosiveMode_TimedStatusEffect-3]
	_ = x[ExplosiveMode_Unknown_32_Chars-4]
}

const _ExplosiveMode_name = "ExplosiveMode_TimedExplosiveMode_ImpactExplosiveMode_ExternalExplosiveMode_TimedStatusEffectExplosiveMode_Unknown_32_Chars"

var _ExplosiveMode_index = [...]uint8{0, 19, 39, 61, 92, 122}

func (i ExplosiveMode) String() string {
	if i >= ExplosiveMode(len(_ExplosiveMode_index)-1) {
		return "ExplosiveMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExplosiveMode_name[_ExplosiveMode_index[i]:_ExplosiveMode_index[i+1]]
}
