// Code generated by "stringer -type=FactionType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FactionType_None-0]
	_ = x[FactionType_SuperEarth-1]
	_ = x[FactionType_Bugs-2]
	_ = x[FactionType_Illuminate-4]
	_ = x[FactionType_Cyborg-8]
	_ = x[FactionType_Wildlife-16]
}

const (
	_FactionType_name_0 = "FactionType_NoneFactionType_SuperEarthFactionType_Bugs"
	_FactionType_name_1 = "FactionType_Illuminate"
	_FactionType_name_2 = "FactionType_Cyborg"
	_FactionType_name_3 = "FactionType_Wildlife"
)

var (
	_FactionType_index_0 = [...]uint8{0, 16, 38, 54}
)

func (i FactionType) String() string {
	switch {
	case i <= 2:
		return _FactionType_name_0[_FactionType_index_0[i]:_FactionType_index_0[i+1]]
	case i == 4:
		return _FactionType_name_1
	case i == 8:
		return _FactionType_name_2
	case i == 16:
		return _FactionType_name_3
	default:
		return "FactionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
