// Code generated by "stringer -type=FireTemplate"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FireTemplate_None-0]
	_ = x[FireTemplate_Small-1]
	_ = x[FireTemplate_Medium-2]
	_ = x[FireTemplate_Large-3]
	_ = x[FireTemplate_Massive-4]
	_ = x[FireTemplate_Count-5]
}

const _FireTemplate_name = "FireTemplate_NoneFireTemplate_SmallFireTemplate_MediumFireTemplate_LargeFireTemplate_MassiveFireTemplate_Count"

var _FireTemplate_index = [...]uint8{0, 17, 35, 54, 72, 92, 110}

func (i FireTemplate) String() string {
	if i >= FireTemplate(len(_FireTemplate_index)-1) {
		return "FireTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FireTemplate_name[_FireTemplate_index[i]:_FireTemplate_index[i+1]]
}
