// Code generated by "stringer -type=HellpodVariant"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HellpodVariant_Payload-0]
	_ = x[HellpodVariant_Reinforce-1]
	_ = x[HellpodVariant_InitialSpawn-2]
}

const _HellpodVariant_name = "HellpodVariant_PayloadHellpodVariant_ReinforceHellpodVariant_InitialSpawn"

var _HellpodVariant_index = [...]uint8{0, 22, 46, 73}

func (i HellpodVariant) String() string {
	if i >= HellpodVariant(len(_HellpodVariant_index)-1) {
		return "HellpodVariant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HellpodVariant_name[_HellpodVariant_index[i]:_HellpodVariant_index[i+1]]
}
