// Code generated by "stringer -type=HitEffectReceiverType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HitEffectReceiverType_None-0]
	_ = x[HitEffectReceiverType_Bug-1]
	_ = x[HitEffectReceiverType_Bug_Armor-2]
	_ = x[HitEffectReceiverType_Cyborg-3]
	_ = x[HitEffectReceiverType_Cyborg_Armor-4]
	_ = x[HitEffectReceiverType_Value_5_Len_16-5]
	_ = x[HitEffectReceiverType_Value_6_Len_24-6]
	_ = x[HitEffectReceiverType_EnergyShield_Illuminate-7]
	_ = x[HitEffectReceiverType_Value_8_Len_29-8]
	_ = x[HitEffectReceiverType_EnergyShield_SE-9]
	_ = x[HitEffectReceiverType_EnergyShield_Backpack-10]
	_ = x[HitEffectReceiverType_Human-11]
	_ = x[HitEffectReceiverType_VehicleHull-12]
	_ = x[HitEffectReceiverType_VehicleWheel-13]
	_ = x[HitEffectReceiverType_TutorialDummy-14]
	_ = x[HitEffectReceiverType_Helldiver-15]
	_ = x[HitEffectReceiverType_BallisticShield_Backpack-16]
	_ = x[HitEffectReceiverType_Value_17_Len_24-17]
	_ = x[HitEffectReceiverType_Value_18_Len_26-18]
	_ = x[HitEffectReceiverType_Value_19_Len_27-19]
	_ = x[HitEffectReceiverType_Value_20_Len_21-20]
	_ = x[HitEffectReceiverType_Value_21_Len_14-21]
	_ = x[HitEffectReceiverType_Value_22_Len_12-22]
	_ = x[HitEffectReceiverType_Count-23]
}

const _HitEffectReceiverType_name = "HitEffectReceiverType_NoneHitEffectReceiverType_BugHitEffectReceiverType_Bug_ArmorHitEffectReceiverType_CyborgHitEffectReceiverType_Cyborg_ArmorHitEffectReceiverType_Value_5_Len_16HitEffectReceiverType_Value_6_Len_24HitEffectReceiverType_EnergyShield_IlluminateHitEffectReceiverType_Value_8_Len_29HitEffectReceiverType_EnergyShield_SEHitEffectReceiverType_EnergyShield_BackpackHitEffectReceiverType_HumanHitEffectReceiverType_VehicleHullHitEffectReceiverType_VehicleWheelHitEffectReceiverType_TutorialDummyHitEffectReceiverType_HelldiverHitEffectReceiverType_BallisticShield_BackpackHitEffectReceiverType_Value_17_Len_24HitEffectReceiverType_Value_18_Len_26HitEffectReceiverType_Value_19_Len_27HitEffectReceiverType_Value_20_Len_21HitEffectReceiverType_Value_21_Len_14HitEffectReceiverType_Value_22_Len_12HitEffectReceiverType_Count"

var _HitEffectReceiverType_index = [...]uint16{0, 26, 51, 82, 110, 144, 180, 216, 261, 297, 334, 377, 404, 437, 471, 506, 537, 583, 620, 657, 694, 731, 768, 805, 832}

func (i HitEffectReceiverType) String() string {
	if i >= HitEffectReceiverType(len(_HitEffectReceiverType_index)-1) {
		return "HitEffectReceiverType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HitEffectReceiverType_name[_HitEffectReceiverType_index[i]:_HitEffectReceiverType_index[i+1]]
}
