// Code generated by "stringer -type=HitEffectDamageType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HitEffectDamageType_None-0]
	_ = x[HitEffectDamageType_PiercingSmall-1]
	_ = x[HitEffectDamageType_PiercingMedium-2]
	_ = x[HitEffectDamageType_PiercingLarge-3]
	_ = x[HitEffectDamageType_PiercingLargeHEAT-4]
	_ = x[HitEffectDamageType_IncendiarySmall-5]
	_ = x[HitEffectDamageType_IncendiaryMedium-6]
	_ = x[HitEffectDamageType_BeamSmall-7]
	_ = x[HitEffectDamageType_BeamLarge-8]
	_ = x[HitEffectDamageType_Blunt-9]
	_ = x[HitEffectDamageType_SlashingSmall-10]
	_ = x[HitEffectDamageType_SlashingLarge-11]
	_ = x[HitEffectDamageType_Value_12_Len_31-12]
	_ = x[HitEffectDamageType_Value_13_Len_37-13]
	_ = x[HitEffectDamageType_Value_14_Len_30-14]
	_ = x[HitEffectDamageType_Value_15_Len_29-15]
	_ = x[HitEffectDamageType_Value_16_Len_28-16]
	_ = x[HitEffectDamageType_Value_17_Len_26-17]
	_ = x[HitEffectDamageType_Count-18]
}

const _HitEffectDamageType_name = "HitEffectDamageType_NoneHitEffectDamageType_PiercingSmallHitEffectDamageType_PiercingMediumHitEffectDamageType_PiercingLargeHitEffectDamageType_PiercingLargeHEATHitEffectDamageType_IncendiarySmallHitEffectDamageType_IncendiaryMediumHitEffectDamageType_BeamSmallHitEffectDamageType_BeamLargeHitEffectDamageType_BluntHitEffectDamageType_SlashingSmallHitEffectDamageType_SlashingLargeHitEffectDamageType_Value_12_Len_31HitEffectDamageType_Value_13_Len_37HitEffectDamageType_Value_14_Len_30HitEffectDamageType_Value_15_Len_29HitEffectDamageType_Value_16_Len_28HitEffectDamageType_Value_17_Len_26HitEffectDamageType_Count"

var _HitEffectDamageType_index = [...]uint16{0, 24, 57, 91, 124, 161, 196, 232, 261, 290, 315, 348, 381, 416, 451, 486, 521, 556, 591, 616}

func (i HitEffectDamageType) String() string {
	if i >= HitEffectDamageType(len(_HitEffectDamageType_index)-1) {
		return "HitEffectDamageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HitEffectDamageType_name[_HitEffectDamageType_index[i]:_HitEffectDamageType_index[i+1]]
}
