// Code generated by "stringer -type=HudMarkerType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HudMarkerType_Generic-0]
	_ = x[HudMarkerType_Enemy-1]
	_ = x[HudMarkerType_EnemyHeavy-2]
	_ = x[HudMarkerType_EnemyMassive-3]
	_ = x[HudMarkerType_EnemyFlyer-4]
	_ = x[HudMarkerType_Squad-5]
	_ = x[HudMarkerType_SquadHeavy-6]
	_ = x[HudMarkerType_SquadMassive-7]
	_ = x[HudMarkerType_SquadFlyer-8]
	_ = x[HudMarkerType_SquadMember-9]
	_ = x[HudMarkerType_Item-10]
	_ = x[HudMarkerType_Sample-11]
	_ = x[HudMarkerType_Intel-12]
	_ = x[HudMarkerType_Vehicle-13]
	_ = x[HudMarkerType_Turret-14]
	_ = x[HudMarkerType_DefensiveEmplacement-15]
	_ = x[HudMarkerType_Mines-16]
	_ = x[HudMarkerType_Value_17_Len_8-17]
	_ = x[HudMarkerType_Objective-18]
	_ = x[HudMarkerType_ObjectiveCode-19]
	_ = x[HudMarkerType_Stratagem-20]
	_ = x[HudMarkerType_Map-21]
	_ = x[HudMarkerType_AvatarReloadRequest-22]
	_ = x[HudMarkerType_AvatarDowned-23]
	_ = x[HudMarkerType_AvatarComms-24]
	_ = x[HudMarkerType_Count-25]
}

const _HudMarkerType_name = "HudMarkerType_GenericHudMarkerType_EnemyHudMarkerType_EnemyHeavyHudMarkerType_EnemyMassiveHudMarkerType_EnemyFlyerHudMarkerType_SquadHudMarkerType_SquadHeavyHudMarkerType_SquadMassiveHudMarkerType_SquadFlyerHudMarkerType_SquadMemberHudMarkerType_ItemHudMarkerType_SampleHudMarkerType_IntelHudMarkerType_VehicleHudMarkerType_TurretHudMarkerType_DefensiveEmplacementHudMarkerType_MinesHudMarkerType_Value_17_Len_8HudMarkerType_ObjectiveHudMarkerType_ObjectiveCodeHudMarkerType_StratagemHudMarkerType_MapHudMarkerType_AvatarReloadRequestHudMarkerType_AvatarDownedHudMarkerType_AvatarCommsHudMarkerType_Count"

var _HudMarkerType_index = [...]uint16{0, 21, 40, 64, 90, 114, 133, 157, 183, 207, 232, 250, 270, 289, 310, 330, 364, 383, 411, 434, 461, 484, 501, 534, 560, 585, 604}

func (i HudMarkerType) String() string {
	if i >= HudMarkerType(len(_HudMarkerType_index)-1) {
		return "HudMarkerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HudMarkerType_name[_HudMarkerType_index[i]:_HudMarkerType_index[i+1]]
}
