// Code generated by "stringer -type=InteractType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InteractType_None-0]
	_ = x[InteractType_PickupWeaponPrimary-1]
	_ = x[InteractType_PickupWeaponSidearm-2]
	_ = x[InteractType_PickupWeaponSupport-3]
	_ = x[InteractType_PickupAmmo-4]
	_ = x[InteractType_PickupHealth-5]
	_ = x[InteractType_PickupGrenades-6]
	_ = x[InteractType_PickupSupplies-7]
	_ = x[InteractType_PickupSuppliesFromRack-8]
	_ = x[InteractType_PickupLootGeneric-9]
	_ = x[InteractType_PickupLootSample-10]
	_ = x[InteractType_PickupSampleContainer-11]
	_ = x[InteractType_PickupHellpod-12]
	_ = x[InteractType_PickupThrowable-13]
	_ = x[InteractType_PressButton-14]
	_ = x[InteractType_PickupSnowball-15]
	_ = x[InteractType_Heal-16]
	_ = x[InteractType_Objective-17]
	_ = x[InteractType_VehicleEntry-18]
	_ = x[InteractType_VehicleStorage-19]
	_ = x[InteractType_Lever-20]
	_ = x[InteractType_MenuScreen-21]
	_ = x[InteractType_MenuScreenHostOnly-22]
	_ = x[InteractType_MenuScreenClientOnly-23]
	_ = x[InteractType_ArmExplosive-24]
	_ = x[InteractType_Elevator-25]
	_ = x[InteractType_Minigame-26]
	_ = x[InteractType_AssistedReload-27]
	_ = x[InteractType_PickupBackpack-28]
	_ = x[InteractType_ObjectiveTerminal-29]
	_ = x[InteractType_PickupCarryable-30]
	_ = x[InteractType_DropOffCarryable-31]
	_ = x[InteractType_Talk-32]
	_ = x[InteractType_RequestMailRewards-33]
	_ = x[InteractType_BallDispenser-34]
	_ = x[InteractType_SyncEmote-35]
	_ = x[InteractType_Assignment-36]
	_ = x[InteractType_Discovery-37]
	_ = x[InteractType_ExtractionEntry-38]
	_ = x[InteractType_TutorialExtractionEntry-39]
	_ = x[InteractType_BackpackGive-40]
	_ = x[InteractType_PickupLootIntel-41]
	_ = x[InteractType_EnableReinforce-42]
	_ = x[InteractType_Stim-43]
	_ = x[InteractType_StimFake-44]
	_ = x[InteractType_AssignmentTalk-45]
	_ = x[InteractType_StateSwitch-46]
	_ = x[InteractType_DeployCarryable-47]
	_ = x[InteractType_Inspect-48]
	_ = x[InteractType_ExplorationReward-49]
	_ = x[InteractType_SuperEarthCache-50]
}

const _InteractType_name = "InteractType_NoneInteractType_PickupWeaponPrimaryInteractType_PickupWeaponSidearmInteractType_PickupWeaponSupportInteractType_PickupAmmoInteractType_PickupHealthInteractType_PickupGrenadesInteractType_PickupSuppliesInteractType_PickupSuppliesFromRackInteractType_PickupLootGenericInteractType_PickupLootSampleInteractType_PickupSampleContainerInteractType_PickupHellpodInteractType_PickupThrowableInteractType_PressButtonInteractType_PickupSnowballInteractType_HealInteractType_ObjectiveInteractType_VehicleEntryInteractType_VehicleStorageInteractType_LeverInteractType_MenuScreenInteractType_MenuScreenHostOnlyInteractType_MenuScreenClientOnlyInteractType_ArmExplosiveInteractType_ElevatorInteractType_MinigameInteractType_AssistedReloadInteractType_PickupBackpackInteractType_ObjectiveTerminalInteractType_PickupCarryableInteractType_DropOffCarryableInteractType_TalkInteractType_RequestMailRewardsInteractType_BallDispenserInteractType_SyncEmoteInteractType_AssignmentInteractType_DiscoveryInteractType_ExtractionEntryInteractType_TutorialExtractionEntryInteractType_BackpackGiveInteractType_PickupLootIntelInteractType_EnableReinforceInteractType_StimInteractType_StimFakeInteractType_AssignmentTalkInteractType_StateSwitchInteractType_DeployCarryableInteractType_InspectInteractType_ExplorationRewardInteractType_SuperEarthCache"

var _InteractType_index = [...]uint16{0, 17, 49, 81, 113, 136, 161, 188, 215, 250, 280, 309, 343, 369, 397, 421, 448, 465, 487, 512, 539, 557, 580, 611, 644, 669, 690, 711, 738, 765, 795, 823, 852, 869, 900, 926, 948, 971, 993, 1021, 1057, 1082, 1110, 1138, 1155, 1176, 1203, 1227, 1255, 1275, 1305, 1333}

func (i InteractType) String() string {
	if i >= InteractType(len(_InteractType_index)-1) {
		return "InteractType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InteractType_name[_InteractType_index[i]:_InteractType_index[i+1]]
}
