// Code generated by "stringer -type=InteractableInjuryType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InteractableInjuryType_None-0]
	_ = x[InteractableInjuryType_BothArms-1]
	_ = x[InteractableInjuryType_OneArm-2]
	_ = x[InteractableInjuryType_BothLegs-3]
	_ = x[InteractableInjuryType_OneLeg-4]
	_ = x[InteractableInjuryType_BothArmsAndLegs-5]
}

const _InteractableInjuryType_name = "InteractableInjuryType_NoneInteractableInjuryType_BothArmsInteractableInjuryType_OneArmInteractableInjuryType_BothLegsInteractableInjuryType_OneLegInteractableInjuryType_BothArmsAndLegs"

var _InteractableInjuryType_index = [...]uint8{0, 27, 58, 87, 118, 147, 185}

func (i InteractableInjuryType) String() string {
	if i >= InteractableInjuryType(len(_InteractableInjuryType_index)-1) {
		return "InteractableInjuryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InteractableInjuryType_name[_InteractableInjuryType_index[i]:_InteractableInjuryType_index[i+1]]
}
