// Code generated by "stringer -type=InteractableMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InteractableMode_OwnerOnly-0]
	_ = x[InteractableMode_Everyone-1]
	_ = x[InteractableMode_EveryoneButOwner-2]
}

const _InteractableMode_name = "InteractableMode_OwnerOnlyInteractableMode_EveryoneInteractableMode_EveryoneButOwner"

var _InteractableMode_index = [...]uint8{0, 26, 51, 84}

func (i InteractableMode) String() string {
	if i >= InteractableMode(len(_InteractableMode_index)-1) {
		return "InteractableMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InteractableMode_name[_InteractableMode_index[i]:_InteractableMode_index[i+1]]
}
