// Code generated by "stringer -type=InventorySlot"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InventorySlot_Value_0_Len_18-0]
	_ = x[InventorySlot_Primary-1]
	_ = x[InventorySlot_Sidearm-2]
	_ = x[InventorySlot_Support-3]
	_ = x[InventorySlot_Grenade-4]
	_ = x[InventorySlot_Value_5_Len_27-5]
	_ = x[InventorySlot_Backpack-6]
	_ = x[InventorySlot_Value_7_Len_18-7]
	_ = x[InventorySlot_Value_8_Len_19-8]
}

const _InventorySlot_name = "InventorySlot_Value_0_Len_18InventorySlot_PrimaryInventorySlot_SidearmInventorySlot_SupportInventorySlot_GrenadeInventorySlot_Value_5_Len_27InventorySlot_BackpackInventorySlot_Value_7_Len_18InventorySlot_Value_8_Len_19"

var _InventorySlot_index = [...]uint8{0, 28, 49, 70, 91, 112, 140, 162, 190, 218}

func (i InventorySlot) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_InventorySlot_index)-1 {
		return "InventorySlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InventorySlot_name[_InventorySlot_index[idx]:_InventorySlot_index[idx+1]]
}
