package enum

type LevelGenerationRegionVariantType uint32

const (
	LevelGenerationRegionVariant_none LevelGenerationRegionVariantType = iota
	LevelGenerationRegionVariant_Value_1_Len_53
	LevelGenerationRegionVariant_Value_2_Len_51
	LevelGenerationRegionVariant_Value_3_Len_46
	LevelGenerationRegionVariant_Value_4_Len_50
	LevelGenerationRegionVariant_region_oasis_prime
	LevelGenerationRegionVariant_region_deciduous_prime
	LevelGenerationRegionVariant_region_arctic_iceland
	LevelGenerationRegionVariant_region_coniferous_prime
	LevelGenerationRegionVariant_Value_9_Len_50
	LevelGenerationRegionVariant_region_generation_test_01
	LevelGenerationRegionVariant_region_sandy_mix
	LevelGenerationRegionVariant_region_magma_prime
	LevelGenerationRegionVariant_Value_13_Len_47
	LevelGenerationRegionVariant_region_primordial_cyborg_factory
	LevelGenerationRegionVariant_region_swamp_cyborg_factory
	LevelGenerationRegionVariant_region_arctic_mountains_and_dunes
	LevelGenerationRegionVariant_region_moor_prime
	LevelGenerationRegionVariant_Value_18_Len_51
	LevelGenerationRegionVariant_Value_19_Len_51
	LevelGenerationRegionVariant_region_moor_massive_fields
	LevelGenerationRegionVariant_region_primordial_inland
	LevelGenerationRegionVariant_region_swamp_dotted_lakes
	LevelGenerationRegionVariant_Value_23_Len_46
	LevelGenerationRegionVariant_Value_24_Len_46
	LevelGenerationRegionVariant_Value_25_Len_58
	LevelGenerationRegionVariant_region_arctic_snowhill
	LevelGenerationRegionVariant_region_swamp_haunted_prime
	LevelGenerationRegionVariant_region_primordial_archipelago
	LevelGenerationRegionVariant_Value_29_Len_47
	LevelGenerationRegionVariant_region_arctic_rocklakes
	LevelGenerationRegionVariant_Value_31_Len_53
	LevelGenerationRegionVariant_Value_32_Len_52
	LevelGenerationRegionVariant_region_magma_lava_islands
	LevelGenerationRegionVariant_region_primordial_bug_wastes
	LevelGenerationRegionVariant_region_shared_city
	LevelGenerationRegionVariant_region_deciduous_mountain
	LevelGenerationRegionVariant_region_moor_mountain
	LevelGenerationRegionVariant_Value_38_Len_56
	LevelGenerationRegionVariant_region_bug_hiveworld_02
	LevelGenerationRegionVariant_region_magma_mountain_lake
	LevelGenerationRegionVariant_region_swamp_prime
	LevelGenerationRegionVariant_region_sandy_cyborg_factory
	LevelGenerationRegionVariant_region_swamp_alpha
	LevelGenerationRegionVariant_Value_44_Len_51
	LevelGenerationRegionVariant_Value_45_Len_56
	LevelGenerationRegionVariant_Value_46_Len_46
	LevelGenerationRegionVariant_region_moor_mountain_island
	LevelGenerationRegionVariant_Value_48_Len_51
	LevelGenerationRegionVariant_region_sandy_mountain_islands
	LevelGenerationRegionVariant_Value_50_Len_55
	LevelGenerationRegionVariant_Value_51_Len_53
	LevelGenerationRegionVariant_region_rift_active
	LevelGenerationRegionVariant_Value_53_Len_56
	LevelGenerationRegionVariant_region_arctic_cyborg_factory
	LevelGenerationRegionVariant_Value_55_Len_50
	LevelGenerationRegionVariant_region_sandy_acid_lakes
	LevelGenerationRegionVariant_region_primordial_volcano_island
	LevelGenerationRegionVariant_region_primordial_prime
	LevelGenerationRegionVariant_Value_59_Len_51
	LevelGenerationRegionVariant_Value_60_Len_45
	LevelGenerationRegionVariant_Value_61_Len_52
	LevelGenerationRegionVariant_Value_62_Len_45
	LevelGenerationRegionVariant_region_sandy_surrounding_mountains
	LevelGenerationRegionVariant_region_moor_cyborg_factory
	LevelGenerationRegionVariant_Value_65_Len_51
	LevelGenerationRegionVariant_region_primordial_coastside
	LevelGenerationRegionVariant_region_swamp_waterless
	LevelGenerationRegionVariant_region_bug_hiveworld_01
	LevelGenerationRegionVariant_region_moor_coastside
	LevelGenerationRegionVariant_region_oasis_mountains
	LevelGenerationRegionVariant_region_arctic_mix
	LevelGenerationRegionVariant_region_arctic_prime
	LevelGenerationRegionVariant_Value_73_Len_54
	LevelGenerationRegionVariant_region_sandy_blocker_mountain
	LevelGenerationRegionVariant_region_swamp_twisting_walls
	LevelGenerationRegionVariant_count
)

func (p LevelGenerationRegionVariantType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

//go:generate go run golang.org/x/tools/cmd/stringer -type=LevelGenerationRegionVariantType
