// Code generated by "stringer -type=LevelGenerationRegionType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelGenerationRegion_none-0]
	_ = x[LevelGenerationRegion_region_generation_testing-1]
	_ = x[LevelGenerationRegion_region_sandy_tutorial-2]
	_ = x[LevelGenerationRegion_region_sandy_base-3]
	_ = x[LevelGenerationRegion_region_sandy_acid-4]
	_ = x[LevelGenerationRegion_region_sandy_moon-5]
	_ = x[LevelGenerationRegion_region_sandy_mineral-6]
	_ = x[LevelGenerationRegion_region_sandy_spiky-7]
	_ = x[LevelGenerationRegion_region_sandy_cyborg_factory-8]
	_ = x[LevelGenerationRegion_region_primordial_tutorial-9]
	_ = x[LevelGenerationRegion_region_primordial_base-10]
	_ = x[LevelGenerationRegion_region_primordial_dead-11]
	_ = x[LevelGenerationRegion_region_primordial_purple-12]
	_ = x[LevelGenerationRegion_region_primordial_blue-13]
	_ = x[LevelGenerationRegion_region_primordial_bug-14]
	_ = x[LevelGenerationRegion_region_magma_base-15]
	_ = x[LevelGenerationRegion_region_arctic_glacier_base-16]
	_ = x[LevelGenerationRegion_region_arctic_glacier_coldrocky-17]
	_ = x[LevelGenerationRegion_region_cyberstan-18]
	_ = x[LevelGenerationRegion_region_moor_baseplanet-19]
	_ = x[LevelGenerationRegion_region_moor_tundra-20]
	_ = x[LevelGenerationRegion_region_moor_arid-21]
	_ = x[LevelGenerationRegion_region_moor_red-22]
	_ = x[LevelGenerationRegion_region_superearth-23]
	_ = x[LevelGenerationRegion_region_swamp_base-24]
	_ = x[LevelGenerationRegion_region_swamp_haunted-25]
	_ = x[LevelGenerationRegion_Value_26_Len_45-26]
	_ = x[LevelGenerationRegion_region_bug_hiveworld-27]
	_ = x[LevelGenerationRegion_region_bug_home-28]
	_ = x[LevelGenerationRegion_count-29]
}

const _LevelGenerationRegionType_name = "LevelGenerationRegion_noneLevelGenerationRegion_region_generation_testingLevelGenerationRegion_region_sandy_tutorialLevelGenerationRegion_region_sandy_baseLevelGenerationRegion_region_sandy_acidLevelGenerationRegion_region_sandy_moonLevelGenerationRegion_region_sandy_mineralLevelGenerationRegion_region_sandy_spikyLevelGenerationRegion_region_sandy_cyborg_factoryLevelGenerationRegion_region_primordial_tutorialLevelGenerationRegion_region_primordial_baseLevelGenerationRegion_region_primordial_deadLevelGenerationRegion_region_primordial_purpleLevelGenerationRegion_region_primordial_blueLevelGenerationRegion_region_primordial_bugLevelGenerationRegion_region_magma_baseLevelGenerationRegion_region_arctic_glacier_baseLevelGenerationRegion_region_arctic_glacier_coldrockyLevelGenerationRegion_region_cyberstanLevelGenerationRegion_region_moor_baseplanetLevelGenerationRegion_region_moor_tundraLevelGenerationRegion_region_moor_aridLevelGenerationRegion_region_moor_redLevelGenerationRegion_region_superearthLevelGenerationRegion_region_swamp_baseLevelGenerationRegion_region_swamp_hauntedLevelGenerationRegion_Value_26_Len_45LevelGenerationRegion_region_bug_hiveworldLevelGenerationRegion_region_bug_homeLevelGenerationRegion_count"

var _LevelGenerationRegionType_index = [...]uint16{0, 26, 73, 116, 155, 194, 233, 275, 315, 364, 412, 456, 500, 546, 590, 633, 672, 720, 773, 811, 855, 895, 933, 970, 1009, 1048, 1090, 1127, 1169, 1206, 1233}

func (i LevelGenerationRegionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LevelGenerationRegionType_index)-1 {
		return "LevelGenerationRegionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LevelGenerationRegionType_name[_LevelGenerationRegionType_index[idx]:_LevelGenerationRegionType_index[idx+1]]
}
