// Code generated by "stringer -type=LocationFlag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocationFlag_None-0]
	_ = x[LocationFlag_Value_1_Len_19-1]
	_ = x[LocationFlag_Value_2_Len_19-2]
	_ = x[LocationFlag_Value_3_Len_17-3]
	_ = x[LocationFlag_Value_4_Len_17-4]
	_ = x[LocationFlag_Value_5_Len_26-5]
	_ = x[LocationFlag_Count-6]
}

const _LocationFlag_name = "LocationFlag_NoneLocationFlag_Value_1_Len_19LocationFlag_Value_2_Len_19LocationFlag_Value_3_Len_17LocationFlag_Value_4_Len_17LocationFlag_Value_5_Len_26LocationFlag_Count"

var _LocationFlag_index = [...]uint8{0, 17, 44, 71, 98, 125, 152, 170}

func (i LocationFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LocationFlag_index)-1 {
		return "LocationFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LocationFlag_name[_LocationFlag_index[idx]:_LocationFlag_index[idx+1]]
}
