// Code generated by "stringer -type=MagazineType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MagazineType_Uniform-0]
	_ = x[MagazineType_Pattern-1]
}

const _MagazineType_name = "MagazineType_UniformMagazineType_Pattern"

var _MagazineType_index = [...]uint8{0, 20, 40}

func (i MagazineType) String() string {
	if i >= MagazineType(len(_MagazineType_index)-1) {
		return "MagazineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MagazineType_name[_MagazineType_index[i]:_MagazineType_index[i+1]]
}
