// Code generated by "stringer -type=MaterialVariableAnimationType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MaterialVariableAnimationType_Linear-0]
	_ = x[MaterialVariableAnimationType_PingPong-1]
}

const _MaterialVariableAnimationType_name = "MaterialVariableAnimationType_LinearMaterialVariableAnimationType_PingPong"

var _MaterialVariableAnimationType_index = [...]uint8{0, 36, 74}

func (i MaterialVariableAnimationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MaterialVariableAnimationType_index)-1 {
		return "MaterialVariableAnimationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaterialVariableAnimationType_name[_MaterialVariableAnimationType_index[idx]:_MaterialVariableAnimationType_index[idx+1]]
}
