// Code generated by "stringer -type=MaterialVariableType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MaterialVariableType_Scalar-0]
	_ = x[MaterialVariableType_Vector2-1]
	_ = x[MaterialVariableType_Vector3-2]
	_ = x[MaterialVariableType_Vector4-3]
}

const _MaterialVariableType_name = "MaterialVariableType_ScalarMaterialVariableType_Vector2MaterialVariableType_Vector3MaterialVariableType_Vector4"

var _MaterialVariableType_index = [...]uint8{0, 27, 55, 83, 111}

func (i MaterialVariableType) String() string {
	if i >= MaterialVariableType(len(_MaterialVariableType_index)-1) {
		return "MaterialVariableType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaterialVariableType_name[_MaterialVariableType_index[i]:_MaterialVariableType_index[i+1]]
}
