// Code generated by "stringer -type=MinimapTerrainType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MinimapTerrainType_Open-0]
	_ = x[MinimapTerrainType_Difficult-1]
	_ = x[MinimapTerrainType_Rocky-2]
	_ = x[MinimapTerrainType_Vegetation-3]
	_ = x[MinimapTerrainType_Impassable-4]
	_ = x[MinimapTerrainType_Bug-5]
}

const _MinimapTerrainType_name = "MinimapTerrainType_OpenMinimapTerrainType_DifficultMinimapTerrainType_RockyMinimapTerrainType_VegetationMinimapTerrainType_ImpassableMinimapTerrainType_Bug"

var _MinimapTerrainType_index = [...]uint8{0, 23, 51, 75, 104, 133, 155}

func (i MinimapTerrainType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MinimapTerrainType_index)-1 {
		return "MinimapTerrainType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MinimapTerrainType_name[_MinimapTerrainType_index[idx]:_MinimapTerrainType_index[idx+1]]
}
