// Code generated by "stringer -type=MountSide"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MountSide_Common-0]
	_ = x[MountSide_Right-1]
	_ = x[MountSide_Left-2]
}

const _MountSide_name = "MountSide_CommonMountSide_RightMountSide_Left"

var _MountSide_index = [...]uint8{0, 16, 31, 45}

func (i MountSide) String() string {
	if i >= MountSide(len(_MountSide_index)-1) {
		return "MountSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MountSide_name[_MountSide_index[i]:_MountSide_index[i+1]]
}
