// Code generated by "stringer -type=NatureLocationTag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NatureLocationTag_none-0]
	_ = x[NatureLocationTag_crater-1]
	_ = x[NatureLocationTag_lake-2]
	_ = x[NatureLocationTag_canyon-3]
}

const _NatureLocationTag_name = "NatureLocationTag_noneNatureLocationTag_craterNatureLocationTag_lakeNatureLocationTag_canyon"

var _NatureLocationTag_index = [...]uint8{0, 22, 46, 68, 92}

func (i NatureLocationTag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NatureLocationTag_index)-1 {
		return "NatureLocationTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NatureLocationTag_name[_NatureLocationTag_index[idx]:_NatureLocationTag_index[idx+1]]
}
