// Code generated by "stringer -type=OperationTag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationTag_None-0]
	_ = x[OperationTag_Value_1_Len_23-1]
	_ = x[OperationTag_Value_2_Len_34-2]
	_ = x[OperationTag_Value_3_Len_25-3]
	_ = x[OperationTag_Value_4_Len_30-4]
	_ = x[OperationTag_Value_5_Len_27-5]
	_ = x[OperationTag_Value_6_Len_24-6]
	_ = x[OperationTag_Value_7_Len_27-7]
	_ = x[OperationTag_Value_8_Len_27-8]
	_ = x[OperationTag_Count-9]
}

const _OperationTag_name = "OperationTag_NoneOperationTag_Value_1_Len_23OperationTag_Value_2_Len_34OperationTag_Value_3_Len_25OperationTag_Value_4_Len_30OperationTag_Value_5_Len_27OperationTag_Value_6_Len_24OperationTag_Value_7_Len_27OperationTag_Value_8_Len_27OperationTag_Count"

var _OperationTag_index = [...]uint8{0, 17, 44, 71, 98, 125, 152, 179, 206, 233, 251}

func (i OperationTag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OperationTag_index)-1 {
		return "OperationTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationTag_name[_OperationTag_index[idx]:_OperationTag_index[idx+1]]
}
