// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationType_Value_0_Len_21-0]
	_ = x[OperationType_Value_1_Len_31-1]
	_ = x[OperationType_Value_2_Len_34-2]
	_ = x[OperationType_Value_3_Len_24-3]
	_ = x[OperationType_Value_4_Len_25-4]
	_ = x[OperationType_Value_5_Len_24-5]
	_ = x[OperationType_Value_6_Len_24-6]
	_ = x[OperationType_Value_7_Len_27-7]
	_ = x[OperationType_Value_8_Len_25-8]
	_ = x[OperationType_Value_9_Len_26-9]
	_ = x[OperationType_Value_10_Len_34-10]
	_ = x[OperationType_Value_11_Len_34-11]
	_ = x[OperationType_Value_12_Len_31-12]
	_ = x[OperationType_Value_13_Len_33-13]
	_ = x[OperationType_None-14]
}

const _OperationType_name = "OperationType_Value_0_Len_21OperationType_Value_1_Len_31OperationType_Value_2_Len_34OperationType_Value_3_Len_24OperationType_Value_4_Len_25OperationType_Value_5_Len_24OperationType_Value_6_Len_24OperationType_Value_7_Len_27OperationType_Value_8_Len_25OperationType_Value_9_Len_26OperationType_Value_10_Len_34OperationType_Value_11_Len_34OperationType_Value_12_Len_31OperationType_Value_13_Len_33OperationType_None"

var _OperationType_index = [...]uint16{0, 28, 56, 84, 112, 140, 168, 196, 224, 252, 280, 309, 338, 367, 396, 414}

func (i OperationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OperationType_index)-1 {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[idx]:_OperationType_index[idx+1]]
}
