// Code generated by "stringer -type=PatrolSetting"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PatrolSetting_Value_0_Len_21-0]
	_ = x[PatrolSetting_Value_1_Len_20-1]
	_ = x[PatrolSetting_Value_2_Len_18-2]
	_ = x[PatrolSetting_None-3]
	_ = x[PatrolSetting_Count-4]
}

const _PatrolSetting_name = "PatrolSetting_Value_0_Len_21PatrolSetting_Value_1_Len_20PatrolSetting_Value_2_Len_18PatrolSetting_NonePatrolSetting_Count"

var _PatrolSetting_index = [...]uint8{0, 28, 56, 84, 102, 121}

func (i PatrolSetting) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PatrolSetting_index)-1 {
		return "PatrolSetting(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PatrolSetting_name[_PatrolSetting_index[idx]:_PatrolSetting_index[idx+1]]
}
