// Code generated by "stringer -type=PlanetType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlanetType_forest-0]
	_ = x[PlanetType_desert-1]
	_ = x[PlanetType_arctic-2]
	_ = x[PlanetType_sandy-3]
	_ = x[PlanetType_savanna-4]
	_ = x[PlanetType_rocky-5]
	_ = x[PlanetType_swamp-6]
	_ = x[PlanetType_snowy_forest-7]
	_ = x[PlanetType_primordial-8]
	_ = x[PlanetType_moor-9]
	_ = x[PlanetType_superearth-10]
	_ = x[PlanetType_bug_hiveworld-11]
	_ = x[PlanetType_magma-12]
	_ = x[PlanetType_oasis-13]
	_ = x[PlanetType_deciduous-14]
	_ = x[PlanetType_coniferous-15]
	_ = x[PlanetType_count-16]
	_ = x[PlanetType_All-4294967295]
}

const (
	_PlanetType_name_0 = "PlanetType_forestPlanetType_desertPlanetType_arcticPlanetType_sandyPlanetType_savannaPlanetType_rockyPlanetType_swampPlanetType_snowy_forestPlanetType_primordialPlanetType_moorPlanetType_superearthPlanetType_bug_hiveworldPlanetType_magmaPlanetType_oasisPlanetType_deciduousPlanetType_coniferousPlanetType_count"
	_PlanetType_name_1 = "PlanetType_All"
)

var (
	_PlanetType_index_0 = [...]uint16{0, 17, 34, 51, 67, 85, 101, 117, 140, 161, 176, 197, 221, 237, 253, 273, 294, 310}
)

func (i PlanetType) String() string {
	switch {
	case i <= 16:
		return _PlanetType_name_0[_PlanetType_index_0[i]:_PlanetType_index_0[i+1]]
	case i == 4294967295:
		return _PlanetType_name_1
	default:
		return "PlanetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
