// Code generated by "stringer -type=ProjectileZeroingQuality"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProjectileZeroingQuality_None-0]
	_ = x[ProjectileZeroingQuality_Cheap-1]
	_ = x[ProjectileZeroingQuality_Normal-2]
	_ = x[ProjectileZeroingQuality_High-3]
	_ = x[ProjectileZeroingQuality_Perfect-4]
	_ = x[ProjectileZeroingQuality_Count-5]
}

const _ProjectileZeroingQuality_name = "ProjectileZeroingQuality_NoneProjectileZeroingQuality_CheapProjectileZeroingQuality_NormalProjectileZeroingQuality_HighProjectileZeroingQuality_PerfectProjectileZeroingQuality_Count"

var _ProjectileZeroingQuality_index = [...]uint8{0, 29, 59, 90, 119, 151, 181}

func (i ProjectileZeroingQuality) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ProjectileZeroingQuality_index)-1 {
		return "ProjectileZeroingQuality(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProjectileZeroingQuality_name[_ProjectileZeroingQuality_index[idx]:_ProjectileZeroingQuality_index[idx+1]]
}
