// Code generated by "stringer -type=ProjectileStatusEffectVolumeTemplate"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProjectileStatusEffectVolumeTemplate_None-0]
	_ = x[ProjectileStatusEffectVolumeTemplate_Flamethrower-1]
	_ = x[ProjectileStatusEffectVolumeTemplate_Acid_Stream-2]
	_ = x[ProjectileStatusEffectVolumeTemplate_Count-3]
}

const _ProjectileStatusEffectVolumeTemplate_name = "ProjectileStatusEffectVolumeTemplate_NoneProjectileStatusEffectVolumeTemplate_FlamethrowerProjectileStatusEffectVolumeTemplate_Acid_StreamProjectileStatusEffectVolumeTemplate_Count"

var _ProjectileStatusEffectVolumeTemplate_index = [...]uint8{0, 41, 90, 138, 180}

func (i ProjectileStatusEffectVolumeTemplate) String() string {
	if i >= ProjectileStatusEffectVolumeTemplate(len(_ProjectileStatusEffectVolumeTemplate_index)-1) {
		return "ProjectileStatusEffectVolumeTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProjectileStatusEffectVolumeTemplate_name[_ProjectileStatusEffectVolumeTemplate_index[i]:_ProjectileStatusEffectVolumeTemplate_index[i+1]]
}
