// Code generated by "stringer -type=RaceType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RaceType_None-0]
	_ = x[RaceType_SuperEarth-1]
	_ = x[RaceType_Bugs-2]
	_ = x[RaceType_Cyborg-3]
	_ = x[RaceType_Illuminate-4]
	_ = x[RaceType_Count-5]
}

const _RaceType_name = "RaceType_NoneRaceType_SuperEarthRaceType_BugsRaceType_CyborgRaceType_IlluminateRaceType_Count"

var _RaceType_index = [...]uint8{0, 13, 32, 45, 60, 79, 93}

func (i RaceType) String() string {
	if i >= RaceType(len(_RaceType_index)-1) {
		return "RaceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RaceType_name[_RaceType_index[i]:_RaceType_index[i+1]]
}
