// Code generated by "stringer -type=RackSide"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RackSide_None-0]
	_ = x[RackSide_Right-1]
	_ = x[RackSide_Left-2]
}

const _RackSide_name = "RackSide_NoneRackSide_RightRackSide_Left"

var _RackSide_index = [...]uint8{0, 13, 27, 40}

func (i RackSide) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RackSide_index)-1 {
		return "RackSide(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RackSide_name[_RackSide_index[idx]:_RackSide_index[idx+1]]
}
