// Code generated by "stringer -type=RaycastTemplate"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RaycastTemplate_Damage-0]
	_ = x[RaycastTemplate_Value_1_Len_37-1]
	_ = x[RaycastTemplate_Value_2_Len_31-2]
	_ = x[RaycastTemplate_DamageLos-3]
	_ = x[RaycastTemplate_IlluminateDamage-4]
	_ = x[RaycastTemplate_Aim-5]
	_ = x[RaycastTemplate_Ground-6]
	_ = x[RaycastTemplate_Value_7_Len_31-7]
	_ = x[RaycastTemplate_Climbable-8]
	_ = x[RaycastTemplate_BidirectionalClimbable-9]
	_ = x[RaycastTemplate_MultiHitClimbable-10]
	_ = x[RaycastTemplate_MotionSnag-11]
	_ = x[RaycastTemplate_Vision-12]
	_ = x[RaycastTemplate_Player-13]
	_ = x[RaycastTemplate_BidirectionalGround-14]
	_ = x[RaycastTemplate_SurfaceEffect-15]
	_ = x[RaycastTemplate_Flyer-16]
	_ = x[RaycastTemplate_Danger-17]
	_ = x[RaycastTemplate_GroundAlign-18]
	_ = x[RaycastTemplate_GroundAlignFindSurface-19]
	_ = x[RaycastTemplate_AimBlock-20]
	_ = x[RaycastTemplate_CameraCollision-21]
	_ = x[RaycastTemplate_Spotting-22]
	_ = x[RaycastTemplate_Terrain-23]
	_ = x[RaycastTemplate_Fire-24]
	_ = x[RaycastTemplate_GroundAll-25]
	_ = x[RaycastTemplate_DamageNoDebris-26]
	_ = x[RaycastTemplate_AimClosest-27]
	_ = x[RaycastTemplate_StaticObstacle-28]
	_ = x[RaycastTemplate_AnyStaticOnlyUniqueBodies-29]
	_ = x[RaycastTemplate_Value_30_Len_25-30]
	_ = x[RaycastTemplate_Count-31]
}

const _RaycastTemplate_name = "RaycastTemplate_DamageRaycastTemplate_Value_1_Len_37RaycastTemplate_Value_2_Len_31RaycastTemplate_DamageLosRaycastTemplate_IlluminateDamageRaycastTemplate_AimRaycastTemplate_GroundRaycastTemplate_Value_7_Len_31RaycastTemplate_ClimbableRaycastTemplate_BidirectionalClimbableRaycastTemplate_MultiHitClimbableRaycastTemplate_MotionSnagRaycastTemplate_VisionRaycastTemplate_PlayerRaycastTemplate_BidirectionalGroundRaycastTemplate_SurfaceEffectRaycastTemplate_FlyerRaycastTemplate_DangerRaycastTemplate_GroundAlignRaycastTemplate_GroundAlignFindSurfaceRaycastTemplate_AimBlockRaycastTemplate_CameraCollisionRaycastTemplate_SpottingRaycastTemplate_TerrainRaycastTemplate_FireRaycastTemplate_GroundAllRaycastTemplate_DamageNoDebrisRaycastTemplate_AimClosestRaycastTemplate_StaticObstacleRaycastTemplate_AnyStaticOnlyUniqueBodiesRaycastTemplate_Value_30_Len_25RaycastTemplate_Count"

var _RaycastTemplate_index = [...]uint16{0, 22, 52, 82, 107, 139, 158, 180, 210, 235, 273, 306, 332, 354, 376, 411, 440, 461, 483, 510, 548, 572, 603, 627, 650, 670, 695, 725, 751, 781, 822, 853, 874}

func (i RaycastTemplate) String() string {
	if i >= RaycastTemplate(len(_RaycastTemplate_index)-1) {
		return "RaycastTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RaycastTemplate_name[_RaycastTemplate_index[i]:_RaycastTemplate_index[i+1]]
}
