// Code generated by "stringer -type=RegionFlag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegionFlag_None-0]
	_ = x[RegionFlag_Value_1_Len_17-1]
	_ = x[RegionFlag_Value_2_Len_17-2]
	_ = x[RegionFlag_Value_3_Len_15-3]
	_ = x[RegionFlag_Value_4_Len_15-4]
	_ = x[RegionFlag_Value_5_Len_24-5]
	_ = x[RegionFlag_Count-6]
}

const _RegionFlag_name = "RegionFlag_NoneRegionFlag_Value_1_Len_17RegionFlag_Value_2_Len_17RegionFlag_Value_3_Len_15RegionFlag_Value_4_Len_15RegionFlag_Value_5_Len_24RegionFlag_Count"

var _RegionFlag_index = [...]uint8{0, 15, 40, 65, 90, 115, 140, 156}

func (i RegionFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RegionFlag_index)-1 {
		return "RegionFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegionFlag_name[_RegionFlag_index[idx]:_RegionFlag_index[idx+1]]
}
