// Code generated by "stringer -type=RingSortingTypes"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RingSortingTypes_saturn_ring-0]
	_ = x[RingSortingTypes_astroid_belt-1]
}

const _RingSortingTypes_name = "RingSortingTypes_saturn_ringRingSortingTypes_astroid_belt"

var _RingSortingTypes_index = [...]uint8{0, 28, 57}

func (i RingSortingTypes) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RingSortingTypes_index)-1 {
		return "RingSortingTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RingSortingTypes_name[_RingSortingTypes_index[idx]:_RingSortingTypes_index[idx+1]]
}
