// Code generated by "stringer -type=RotationType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RotationType_None-0]
	_ = x[RotationType_FollowWindGround-1]
	_ = x[RotationType_FollowWindFalling-2]
	_ = x[RotationType_AlignWithCamera-3]
}

const _RotationType_name = "RotationType_NoneRotationType_FollowWindGroundRotationType_FollowWindFallingRotationType_AlignWithCamera"

var _RotationType_index = [...]uint8{0, 17, 46, 76, 104}

func (i RotationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RotationType_index)-1 {
		return "RotationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RotationType_name[_RotationType_index[idx]:_RotationType_index[idx+1]]
}
