// Code generated by "stringer -type=SampleType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SampleType_None-0]
	_ = x[SampleType_Bio-1]
	_ = x[SampleType_Legendarium-2]
	_ = x[SampleType_Super-3]
	_ = x[SampleType_UsedCount-4]
	_ = x[SampleType_Tech-5]
	_ = x[SampleType_Artifact-6]
	_ = x[SampleType_Oil-7]
	_ = x[SampleType_Spice-8]
	_ = x[SampleType_Uranium-9]
	_ = x[SampleType_Count-10]
	_ = x[SampleType_Any-11]
}

const _SampleType_name = "SampleType_NoneSampleType_BioSampleType_LegendariumSampleType_SuperSampleType_UsedCountSampleType_TechSampleType_ArtifactSampleType_OilSampleType_SpiceSampleType_UraniumSampleType_CountSampleType_Any"

var _SampleType_index = [...]uint8{0, 15, 29, 51, 67, 87, 102, 121, 135, 151, 169, 185, 199}

func (i SampleType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SampleType_index)-1 {
		return "SampleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SampleType_name[_SampleType_index[idx]:_SampleType_index[idx+1]]
}
