// Code generated by "stringer -type=SeekingMissileTargetingMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeekingMissileTargetingMode_Behavior-0]
	_ = x[SeekingMissileTargetingMode_Guidance-1]
	_ = x[SeekingMissileTargetingMode_TargetLock-2]
	_ = x[SeekingMissileTargetingMode_External-3]
	_ = x[SeekingMissileTargetingMode_Count-4]
}

const _SeekingMissileTargetingMode_name = "SeekingMissileTargetingMode_BehaviorSeekingMissileTargetingMode_GuidanceSeekingMissileTargetingMode_TargetLockSeekingMissileTargetingMode_ExternalSeekingMissileTargetingMode_Count"

var _SeekingMissileTargetingMode_index = [...]uint8{0, 36, 72, 110, 146, 179}

func (i SeekingMissileTargetingMode) String() string {
	if i >= SeekingMissileTargetingMode(len(_SeekingMissileTargetingMode_index)-1) {
		return "SeekingMissileTargetingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SeekingMissileTargetingMode_name[_SeekingMissileTargetingMode_index[i]:_SeekingMissileTargetingMode_index[i+1]]
}
