// Code generated by "stringer -type=SolarSystemPlanetType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SolarSystemPlanetType_earthsized-0]
	_ = x[SolarSystemPlanetType_sun-1]
	_ = x[SolarSystemPlanetType_moon-2]
	_ = x[SolarSystemPlanetType_gasgiant-3]
	_ = x[SolarSystemPlanetType_ring-4]
}

const _SolarSystemPlanetType_name = "SolarSystemPlanetType_earthsizedSolarSystemPlanetType_sunSolarSystemPlanetType_moonSolarSystemPlanetType_gasgiantSolarSystemPlanetType_ring"

var _SolarSystemPlanetType_index = [...]uint8{0, 32, 57, 83, 113, 139}

func (i SolarSystemPlanetType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SolarSystemPlanetType_index)-1 {
		return "SolarSystemPlanetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SolarSystemPlanetType_name[_SolarSystemPlanetType_index[idx]:_SolarSystemPlanetType_index[idx+1]]
}
