// Code generated by "stringer -type=StampOverlapGroups"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StampOverlapGroup_None-0]
	_ = x[StampOverlapGroups_Value_1_Len_26-1]
	_ = x[StampOverlapGroup_A-2]
	_ = x[StampOverlapGroup_B-3]
	_ = x[StampOverlapGroup_C-4]
	_ = x[StampOverlapGroup_D-5]
	_ = x[StampOverlapGroup_E-6]
	_ = x[StampOverlapGroup_F-7]
	_ = x[StampOverlapGroup_G-8]
	_ = x[StampOverlapGroups_Value_9_Len_24-9]
}

const _StampOverlapGroups_name = "StampOverlapGroup_NoneStampOverlapGroups_Value_1_Len_26StampOverlapGroup_AStampOverlapGroup_BStampOverlapGroup_CStampOverlapGroup_DStampOverlapGroup_EStampOverlapGroup_FStampOverlapGroup_GStampOverlapGroups_Value_9_Len_24"

var _StampOverlapGroups_index = [...]uint8{0, 22, 55, 74, 93, 112, 131, 150, 169, 188, 221}

func (i StampOverlapGroups) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StampOverlapGroups_index)-1 {
		return "StampOverlapGroups(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StampOverlapGroups_name[_StampOverlapGroups_index[idx]:_StampOverlapGroups_index[idx+1]]
}
