// Code generated by "stringer -type=StampEntrySatelliteType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StampEntrySatelliteType_None-0]
	_ = x[StampEntrySatelliteType_General-1]
}

const _StampEntrySatelliteType_name = "StampEntrySatelliteType_NoneStampEntrySatelliteType_General"

var _StampEntrySatelliteType_index = [...]uint8{0, 28, 59}

func (i StampEntrySatelliteType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StampEntrySatelliteType_index)-1 {
		return "StampEntrySatelliteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StampEntrySatelliteType_name[_StampEntrySatelliteType_index[idx]:_StampEntrySatelliteType_index[idx+1]]
}
