// Code generated by "stringer -type=StampEntryType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StampEntryType_stop-0]
	_ = x[StampEntryType_connection-1]
	_ = x[StampEntryType_junction-2]
}

const _StampEntryType_name = "StampEntryType_stopStampEntryType_connectionStampEntryType_junction"

var _StampEntryType_index = [...]uint8{0, 19, 44, 67}

func (i StampEntryType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StampEntryType_index)-1 {
		return "StampEntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StampEntryType_name[_StampEntryType_index[idx]:_StampEntryType_index[idx+1]]
}
