// Code generated by "stringer -type=StampSplineType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StampSpline_Path-0]
	_ = x[StampSpline_SuperEarthRoad-1]
	_ = x[StampSpline_BugRoad-2]
	_ = x[StampSpline_BotRoad-3]
	_ = x[StampSpline_IlluminateRoad-4]
	_ = x[StampSpline_Count-5]
	_ = x[StampSpline_Any-6]
}

const _StampSplineType_name = "StampSpline_PathStampSpline_SuperEarthRoadStampSpline_BugRoadStampSpline_BotRoadStampSpline_IlluminateRoadStampSpline_CountStampSpline_Any"

var _StampSplineType_index = [...]uint8{0, 16, 42, 61, 80, 106, 123, 138}

func (i StampSplineType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StampSplineType_index)-1 {
		return "StampSplineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StampSplineType_name[_StampSplineType_index[idx]:_StampSplineType_index[idx+1]]
}
