// Code generated by "stringer -type=StampExtensionType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StampExtension_Expand-0]
	_ = x[StampExtension_Location-1]
}

const _StampExtensionType_name = "StampExtension_ExpandStampExtension_Location"

var _StampExtensionType_index = [...]uint8{0, 21, 44}

func (i StampExtensionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StampExtensionType_index)-1 {
		return "StampExtensionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StampExtensionType_name[_StampExtensionType_index[idx]:_StampExtensionType_index[idx+1]]
}
