// Code generated by "stringer -type=StatusEffectTemplateType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusEffectTemplateType_None-0]
	_ = x[StatusEffectTemplateType_Flamethrower-1]
	_ = x[StatusEffectTemplateType_Barbwire-2]
	_ = x[StatusEffectTemplateType_Fire-3]
	_ = x[StatusEffectTemplateType_Acid_Splash-4]
	_ = x[StatusEffectTemplateType_Acid_Stream-5]
	_ = x[StatusEffectTemplateType_Water-6]
	_ = x[StatusEffectTemplateType_Electric-7]
	_ = x[StatusEffectTemplateType_NukeRadiation-8]
	_ = x[StatusEffectTemplateType_Snow-9]
	_ = x[StatusEffectTemplateType_Mud-10]
	_ = x[StatusEffectTemplateType_Sand-11]
	_ = x[StatusEffectTemplateType_Pure_Damage-12]
	_ = x[StatusEffectTemplateType_Thornbush-13]
	_ = x[StatusEffectTemplateType_Smoke-14]
	_ = x[StatusEffectTemplateType_StaticField-15]
	_ = x[StatusEffectTemplateType_Gas-16]
	_ = x[StatusEffectTemplateType_Hidden-17]
	_ = x[StatusEffectTemplateType_ExtremeCold-18]
	_ = x[StatusEffectTemplateType_Value_19_Len_36-19]
	_ = x[StatusEffectTemplateType_Freezing-20]
	_ = x[StatusEffectTemplateType_Value_21_Len_37-21]
	_ = x[StatusEffectTemplateType_Value_22_Len_39-22]
	_ = x[StatusEffectTemplateType_Value_23_Len_34-23]
	_ = x[StatusEffectTemplateType_Value_24_Len_34-24]
	_ = x[StatusEffectTemplateType_Value_25_Len_33-25]
	_ = x[StatusEffectTemplateType_Value_26_Len_34-26]
	_ = x[StatusEffectTemplateType_Value_27_Len_34-27]
	_ = x[StatusEffectTemplateType_Value_28_Len_34-28]
	_ = x[StatusEffectTemplateType_Value_29_Len_29-29]
	_ = x[StatusEffectTemplateType_Count-30]
}

const _StatusEffectTemplateType_name = "StatusEffectTemplateType_NoneStatusEffectTemplateType_FlamethrowerStatusEffectTemplateType_BarbwireStatusEffectTemplateType_FireStatusEffectTemplateType_Acid_SplashStatusEffectTemplateType_Acid_StreamStatusEffectTemplateType_WaterStatusEffectTemplateType_ElectricStatusEffectTemplateType_NukeRadiationStatusEffectTemplateType_SnowStatusEffectTemplateType_MudStatusEffectTemplateType_SandStatusEffectTemplateType_Pure_DamageStatusEffectTemplateType_ThornbushStatusEffectTemplateType_SmokeStatusEffectTemplateType_StaticFieldStatusEffectTemplateType_GasStatusEffectTemplateType_HiddenStatusEffectTemplateType_ExtremeColdStatusEffectTemplateType_Value_19_Len_36StatusEffectTemplateType_FreezingStatusEffectTemplateType_Value_21_Len_37StatusEffectTemplateType_Value_22_Len_39StatusEffectTemplateType_Value_23_Len_34StatusEffectTemplateType_Value_24_Len_34StatusEffectTemplateType_Value_25_Len_33StatusEffectTemplateType_Value_26_Len_34StatusEffectTemplateType_Value_27_Len_34StatusEffectTemplateType_Value_28_Len_34StatusEffectTemplateType_Value_29_Len_29StatusEffectTemplateType_Count"

var _StatusEffectTemplateType_index = [...]uint16{0, 29, 66, 99, 128, 164, 200, 230, 263, 301, 330, 358, 387, 423, 457, 487, 523, 551, 582, 618, 658, 691, 731, 771, 811, 851, 891, 931, 971, 1011, 1051, 1081}

func (i StatusEffectTemplateType) String() string {
	if i >= StatusEffectTemplateType(len(_StatusEffectTemplateType_index)-1) {
		return "StatusEffectTemplateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusEffectTemplateType_name[_StatusEffectTemplateType_index[i]:_StatusEffectTemplateType_index[i+1]]
}
