// Code generated by "stringer -type=StatusEffectType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusEffectType_None-0]
	_ = x[StatusEffectType_Blind-1]
	_ = x[StatusEffectType_Bleed-2]
	_ = x[StatusEffectType_Deaf-3]
	_ = x[StatusEffectType_Confusion-4]
	_ = x[StatusEffectType_Fire-5]
	_ = x[StatusEffectType_Value_6_Len_27-6]
	_ = x[StatusEffectType_Value_7_Len_21-7]
	_ = x[StatusEffectType_Slowed-8]
	_ = x[StatusEffectType_Rooted-9]
	_ = x[StatusEffectType_Acid_Splash-10]
	_ = x[StatusEffectType_Acid_Stream-11]
	_ = x[StatusEffectType_Thermite-12]
	_ = x[StatusEffectType_Cyborg_Fire-13]
	_ = x[StatusEffectType_Value_14_Len_23-14]
	_ = x[StatusEffectType_Sand-15]
	_ = x[StatusEffectType_Mud-16]
	_ = x[StatusEffectType_Snow-17]
	_ = x[StatusEffectType_Submerged-18]
	_ = x[StatusEffectType_Thornbush-19]
	_ = x[StatusEffectType_Value_20_Len_23-20]
	_ = x[StatusEffectType_Barbwire-21]
	_ = x[StatusEffectType_BushSmall-22]
	_ = x[StatusEffectType_BushLarge-23]
	_ = x[StatusEffectType_Pure_Damage-24]
	_ = x[StatusEffectType_Value_25_Len_23-25]
	_ = x[StatusEffectType_StimStamina-26]
	_ = x[StatusEffectType_StimHeal-27]
	_ = x[StatusEffectType_DownedStimHeal-28]
	_ = x[StatusEffectType_DownedStimVisual-29]
	_ = x[StatusEffectType_StimCooldown-30]
	_ = x[StatusEffectType_BurningHeavy-31]
	_ = x[StatusEffectType_RadiationLight-32]
	_ = x[StatusEffectType_RadiationHeavy-33]
	_ = x[StatusEffectType_Electric-34]
	_ = x[StatusEffectType_Hidden-35]
	_ = x[StatusEffectType_StunSmall-36]
	_ = x[StatusEffectType_StunMedium-37]
	_ = x[StatusEffectType_StunLarge-38]
	_ = x[StatusEffectType_StunMassive-39]
	_ = x[StatusEffectType_StunIlluminate-40]
	_ = x[StatusEffectType_Gas-41]
	_ = x[StatusEffectType_Value_42_Len_26-42]
	_ = x[StatusEffectType_Value_43_Len_30-43]
	_ = x[StatusEffectType_Value_44_Len_36-44]
	_ = x[StatusEffectType_Value_45_Len_36-45]
	_ = x[StatusEffectType_Flashlighted-46]
	_ = x[StatusEffectType_Smoke_Covered-47]
	_ = x[StatusEffectType_BackpackChemicals-48]
	_ = x[StatusEffectType_IntenseHeat-49]
	_ = x[StatusEffectType_ExtremeCold-50]
	_ = x[StatusEffectType_Value_51_Len_23-51]
	_ = x[StatusEffectType_Value_52_Len_26-52]
	_ = x[StatusEffectType_Value_53_Len_26-53]
	_ = x[StatusEffectType_Value_54_Len_26-54]
	_ = x[StatusEffectType_Value_55_Len_25-55]
	_ = x[StatusEffectType_Value_56_Len_26-56]
	_ = x[StatusEffectType_Value_57_Len_26-57]
	_ = x[StatusEffectType_Value_58_Len_26-58]
	_ = x[StatusEffectType_Value_59_Len_27-59]
	_ = x[StatusEffectType_Value_60_Len_34-60]
	_ = x[StatusEffectType_Value_61_Len_36-61]
	_ = x[StatusEffectType_Value_62_Len_36-62]
	_ = x[StatusEffectType_Value_63_Len_36-63]
	_ = x[StatusEffectType_Value_64_Len_29-64]
	_ = x[StatusEffectType_Value_65_Len_45-65]
	_ = x[StatusEffectType_Value_66_Len_36-66]
	_ = x[StatusEffectType_Value_67_Len_25-67]
	_ = x[StatusEffectType_Count-68]
}

const _StatusEffectType_name = "StatusEffectType_NoneStatusEffectType_BlindStatusEffectType_BleedStatusEffectType_DeafStatusEffectType_ConfusionStatusEffectType_FireStatusEffectType_Value_6_Len_27StatusEffectType_Value_7_Len_21StatusEffectType_SlowedStatusEffectType_RootedStatusEffectType_Acid_SplashStatusEffectType_Acid_StreamStatusEffectType_ThermiteStatusEffectType_Cyborg_FireStatusEffectType_Value_14_Len_23StatusEffectType_SandStatusEffectType_MudStatusEffectType_SnowStatusEffectType_SubmergedStatusEffectType_ThornbushStatusEffectType_Value_20_Len_23StatusEffectType_BarbwireStatusEffectType_BushSmallStatusEffectType_BushLargeStatusEffectType_Pure_DamageStatusEffectType_Value_25_Len_23StatusEffectType_StimStaminaStatusEffectType_StimHealStatusEffectType_DownedStimHealStatusEffectType_DownedStimVisualStatusEffectType_StimCooldownStatusEffectType_BurningHeavyStatusEffectType_RadiationLightStatusEffectType_RadiationHeavyStatusEffectType_ElectricStatusEffectType_HiddenStatusEffectType_StunSmallStatusEffectType_StunMediumStatusEffectType_StunLargeStatusEffectType_StunMassiveStatusEffectType_StunIlluminateStatusEffectType_GasStatusEffectType_Value_42_Len_26StatusEffectType_Value_43_Len_30StatusEffectType_Value_44_Len_36StatusEffectType_Value_45_Len_36StatusEffectType_FlashlightedStatusEffectType_Smoke_CoveredStatusEffectType_BackpackChemicalsStatusEffectType_IntenseHeatStatusEffectType_ExtremeColdStatusEffectType_Value_51_Len_23StatusEffectType_Value_52_Len_26StatusEffectType_Value_53_Len_26StatusEffectType_Value_54_Len_26StatusEffectType_Value_55_Len_25StatusEffectType_Value_56_Len_26StatusEffectType_Value_57_Len_26StatusEffectType_Value_58_Len_26StatusEffectType_Value_59_Len_27StatusEffectType_Value_60_Len_34StatusEffectType_Value_61_Len_36StatusEffectType_Value_62_Len_36StatusEffectType_Value_63_Len_36StatusEffectType_Value_64_Len_29StatusEffectType_Value_65_Len_45StatusEffectType_Value_66_Len_36StatusEffectType_Value_67_Len_25StatusEffectType_Count"

var _StatusEffectType_index = [...]uint16{0, 21, 43, 65, 86, 112, 133, 164, 195, 218, 241, 269, 297, 322, 350, 382, 403, 423, 444, 470, 496, 528, 553, 579, 605, 633, 665, 693, 718, 749, 782, 811, 840, 871, 902, 927, 950, 976, 1003, 1029, 1057, 1088, 1108, 1140, 1172, 1204, 1236, 1265, 1295, 1329, 1357, 1385, 1417, 1449, 1481, 1513, 1545, 1577, 1609, 1641, 1673, 1705, 1737, 1769, 1801, 1833, 1865, 1897, 1929, 1951}

func (i StatusEffectType) String() string {
	if i >= StatusEffectType(len(_StatusEffectType_index)-1) {
		return "StatusEffectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusEffectType_name[_StatusEffectType_index[i]:_StatusEffectType_index[i+1]]
}
