// Code generated by "stringer -type=SubRegionType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SubRegionType_None-0]
	_ = x[SubRegionType_Blocker_Bottom-1]
	_ = x[SubRegionType_Blocker_Bottom_B-2]
	_ = x[SubRegionType_Blocker_Bottom_C-3]
	_ = x[SubRegionType_Blocker_General-4]
	_ = x[SubRegionType_Blocker_General_B-5]
	_ = x[SubRegionType_Blocker_General_C-6]
	_ = x[SubRegionType_A-7]
	_ = x[SubRegionType_B-8]
	_ = x[SubRegionType_C-9]
	_ = x[SubRegionType_D-10]
	_ = x[SubRegionType_E-11]
	_ = x[SubRegionType_F-12]
	_ = x[SubRegionType_G-13]
	_ = x[SubRegionType_H-14]
	_ = x[SubRegionType_I-15]
	_ = x[SubRegionType_J-16]
	_ = x[SubRegionType_ExtraResources-17]
	_ = x[SubRegionType_Bugs-18]
	_ = x[SubRegionType_Value_19_Len_26-19]
	_ = x[SubRegionType_Value_20_Len_25-20]
	_ = x[SubRegionType_Cyborgs-21]
	_ = x[SubRegionType_Value_22_Len_24-22]
	_ = x[SubRegionType_Illuminate-23]
	_ = x[SubRegionType_Value_24_Len_20-24]
	_ = x[SubRegionType_Value_25_Len_25-25]
	_ = x[SubRegionType_Value_26_Len_27-26]
	_ = x[SubRegionType_Value_27_Len_27-27]
	_ = x[SubRegionType_Value_28_Len_27-28]
	_ = x[SubRegionType_Value_29_Len_27-29]
	_ = x[SubRegionType_Value_30_Len_27-30]
	_ = x[SubRegionType_Value_31_Len_27-31]
	_ = x[SubRegionType_Value_32_Len_27-32]
	_ = x[SubRegionType_Value_33_Len_27-33]
	_ = x[SubRegionType_Value_34_Len_27-34]
	_ = x[SubRegionType_Value_35_Len_18-35]
	_ = x[SubRegionType_Value_36_Len_35-36]
	_ = x[SubRegionType_Value_37_Len_35-37]
	_ = x[SubRegionType_Value_38_Len_35-38]
	_ = x[SubRegionType_Value_39_Len_35-39]
	_ = x[SubRegionType_Value_40_Len_19-40]
}

const _SubRegionType_name = "SubRegionType_NoneSubRegionType_Blocker_BottomSubRegionType_Blocker_Bottom_BSubRegionType_Blocker_Bottom_CSubRegionType_Blocker_GeneralSubRegionType_Blocker_General_BSubRegionType_Blocker_General_CSubRegionType_ASubRegionType_BSubRegionType_CSubRegionType_DSubRegionType_ESubRegionType_FSubRegionType_GSubRegionType_HSubRegionType_ISubRegionType_JSubRegionType_ExtraResourcesSubRegionType_BugsSubRegionType_Value_19_Len_26SubRegionType_Value_20_Len_25SubRegionType_CyborgsSubRegionType_Value_22_Len_24SubRegionType_IlluminateSubRegionType_Value_24_Len_20SubRegionType_Value_25_Len_25SubRegionType_Value_26_Len_27SubRegionType_Value_27_Len_27SubRegionType_Value_28_Len_27SubRegionType_Value_29_Len_27SubRegionType_Value_30_Len_27SubRegionType_Value_31_Len_27SubRegionType_Value_32_Len_27SubRegionType_Value_33_Len_27SubRegionType_Value_34_Len_27SubRegionType_Value_35_Len_18SubRegionType_Value_36_Len_35SubRegionType_Value_37_Len_35SubRegionType_Value_38_Len_35SubRegionType_Value_39_Len_35SubRegionType_Value_40_Len_19"

var _SubRegionType_index = [...]uint16{0, 18, 46, 76, 106, 135, 166, 197, 212, 227, 242, 257, 272, 287, 302, 317, 332, 347, 375, 393, 422, 451, 472, 501, 525, 554, 583, 612, 641, 670, 699, 728, 757, 786, 815, 844, 873, 902, 931, 960, 989, 1018}

func (i SubRegionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SubRegionType_index)-1 {
		return "SubRegionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubRegionType_name[_SubRegionType_index[idx]:_SubRegionType_index[idx+1]]
}
