// Code generated by "stringer -type=SubRegionType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SubRegionType_None-0]
	_ = x[SubRegionType_Blocker_Bottom-1]
	_ = x[SubRegionType_Blocker_Bottom_B-2]
	_ = x[SubRegionType_Blocker_Bottom_C-3]
	_ = x[SubRegionType_Blocker_General-4]
	_ = x[SubRegionType_Blocker_General_B-5]
	_ = x[SubRegionType_Blocker_General_C-6]
	_ = x[SubRegionType_A-7]
	_ = x[SubRegionType_B-8]
	_ = x[SubRegionType_C-9]
	_ = x[SubRegionType_D-10]
	_ = x[SubRegionType_E-11]
	_ = x[SubRegionType_F-12]
	_ = x[SubRegionType_G-13]
	_ = x[SubRegionType_H-14]
	_ = x[SubRegionType_I-15]
	_ = x[SubRegionType_J-16]
	_ = x[SubRegionType_ExtraResources-17]
	_ = x[SubRegionType_Bugs-18]
	_ = x[SubRegionType_Value_19_Len_26-19]
	_ = x[SubRegionType_Value_20_Len_25-20]
	_ = x[SubRegionType_Cyborgs-21]
	_ = x[SubRegionType_Value_22_Len_24-22]
	_ = x[SubRegionType_Illuminate-23]
	_ = x[SubRegionType_Value_24_Len_20-24]
	_ = x[SubRegionType_Value_25_Len_25-25]
	_ = x[SubRegionType_Value_26_Len_27-26]
	_ = x[SubRegionType_Bugs_Colony_A-27]
	_ = x[SubRegionType_Bugs_Colony_B-28]
	_ = x[SubRegionType_Bugs_Colony_C-29]
	_ = x[SubRegionType_Bugs_Colony_D-30]
	_ = x[SubRegionType_Bots_Colony_A-31]
	_ = x[SubRegionType_Bots_Colony_B-32]
	_ = x[SubRegionType_Bots_Colony_C-33]
	_ = x[SubRegionType_Bots_Colony_D-34]
	_ = x[SubRegionType_Hive-35]
	_ = x[SubRegionType_Illuminate_Colonies_A-36]
	_ = x[SubRegionType_Illuminate_Colonies_B-37]
	_ = x[SubRegionType_Illuminate_Colonies_C-38]
	_ = x[SubRegionType_Illuminate_Colonies_D-39]
	_ = x[SubRegionType_Count-40]
}

const _SubRegionType_name = "SubRegionType_NoneSubRegionType_Blocker_BottomSubRegionType_Blocker_Bottom_BSubRegionType_Blocker_Bottom_CSubRegionType_Blocker_GeneralSubRegionType_Blocker_General_BSubRegionType_Blocker_General_CSubRegionType_ASubRegionType_BSubRegionType_CSubRegionType_DSubRegionType_ESubRegionType_FSubRegionType_GSubRegionType_HSubRegionType_ISubRegionType_JSubRegionType_ExtraResourcesSubRegionType_BugsSubRegionType_Value_19_Len_26SubRegionType_Value_20_Len_25SubRegionType_CyborgsSubRegionType_Value_22_Len_24SubRegionType_IlluminateSubRegionType_Value_24_Len_20SubRegionType_Value_25_Len_25SubRegionType_Value_26_Len_27SubRegionType_Bugs_Colony_ASubRegionType_Bugs_Colony_BSubRegionType_Bugs_Colony_CSubRegionType_Bugs_Colony_DSubRegionType_Bots_Colony_ASubRegionType_Bots_Colony_BSubRegionType_Bots_Colony_CSubRegionType_Bots_Colony_DSubRegionType_HiveSubRegionType_Illuminate_Colonies_ASubRegionType_Illuminate_Colonies_BSubRegionType_Illuminate_Colonies_CSubRegionType_Illuminate_Colonies_DSubRegionType_Count"

var _SubRegionType_index = [...]uint16{0, 18, 46, 76, 106, 135, 166, 197, 212, 227, 242, 257, 272, 287, 302, 317, 332, 347, 375, 393, 422, 451, 472, 501, 525, 554, 583, 612, 639, 666, 693, 720, 747, 774, 801, 828, 846, 881, 916, 951, 986, 1005}

func (i SubRegionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SubRegionType_index)-1 {
		return "SubRegionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubRegionType_name[_SubRegionType_index[idx]:_SubRegionType_index[idx+1]]
}
