// Code generated by "stringer -type=SubRegionHeight"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SubRegionHeight_None-0]
	_ = x[SubRegionHeight_Bottom_Flat-1]
	_ = x[SubRegionHeight_Low-2]
	_ = x[SubRegionHeight_Middle-3]
	_ = x[SubRegionHeight_High-4]
	_ = x[SubRegionHeight_Value_5_Len_32-5]
	_ = x[SubRegionHeight_All-4294967295]
}

const (
	_SubRegionHeight_name_0 = "SubRegionHeight_NoneSubRegionHeight_Bottom_FlatSubRegionHeight_LowSubRegionHeight_MiddleSubRegionHeight_HighSubRegionHeight_Value_5_Len_32"
	_SubRegionHeight_name_1 = "SubRegionHeight_All"
)

var (
	_SubRegionHeight_index_0 = [...]uint8{0, 20, 47, 66, 88, 108, 138}
)

func (i SubRegionHeight) String() string {
	switch {
	case i <= 5:
		return _SubRegionHeight_name_0[_SubRegionHeight_index_0[i]:_SubRegionHeight_index_0[i+1]]
	case i == 4294967295:
		return _SubRegionHeight_name_1
	default:
		return "SubRegionHeight(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
