// Code generated by "stringer -type=Tag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Tag_None-0]
	_ = x[Tag_Character-1]
	_ = x[Tag_Mountable-2]
	_ = x[Tag_Deployable-4]
	_ = x[Tag_IgnoreBroadphase-8]
	_ = x[Tag_SupportMountable-16]
	_ = x[Tag_SurvivesStateTransition-32]
	_ = x[Tag_Objective-64]
	_ = x[Tag_Defense-128]
	_ = x[Tag_LandingZone-256]
	_ = x[Tag_Eagle-512]
	_ = x[Tag_Discoverable-2048]
	_ = x[Tag_Beacon-4096]
	_ = x[Tag_Charger-8192]
	_ = x[Tag_Heavy-16384]
	_ = x[Tag_RemoveOnMigration-32768]
	_ = x[Tag_EnemyFlying-65536]
	_ = x[Tag_CanHellpodAttachTo-131072]
	_ = x[Tag_TwoHandedThrowable-262144]
	_ = x[Tag_AIObjectiveTarget-524288]
	_ = x[Tag_Value_100000_Len_28-1048576]
	_ = x[Tag_CanArc-2097152]
	_ = x[Tag_NoTransportDeployment-4194304]
	_ = x[Tag_NoAimAssist-8388608]
	_ = x[Tag_IgnoreEncounterCount-16777216]
	_ = x[Tag_IgnoredByEnemies-33554432]
	_ = x[Tag_InvalidEnemyTarget-67108864]
	_ = x[Tag_CanBeLockedOn-134217728]
	_ = x[Tag_NoStatTracking-268435456]
	_ = x[Tag_SuitableMeleeTarget-536870912]
	_ = x[Tag_Value_40000000_Len_29-1073741824]
	_ = x[Tag_Value_80000000_Len_17-2147483648]
	_ = x[Tag_Value_100000000_Len_28-4294967296]
	_ = x[Tag_Value_200000000_Len_26-8589934592]
	_ = x[Tag_Value_400000000_Len_22-17179869184]
	_ = x[Tag_Value_800000000_Len_12-34359738368]
	_ = x[Tag_Value_1000000000_Len_21-68719476736]
	_ = x[Tag_Value_2000000000_Len_26-137438953472]
	_ = x[Tag_Value_4000000000_Len_13-274877906944]
	_ = x[Tag_Value_8000000000_Len_20-549755813888]
}

const _Tag_name = "Tag_NoneTag_CharacterTag_MountableTag_DeployableTag_IgnoreBroadphaseTag_SupportMountableTag_SurvivesStateTransitionTag_ObjectiveTag_DefenseTag_LandingZoneTag_EagleTag_DiscoverableTag_BeaconTag_ChargerTag_HeavyTag_RemoveOnMigrationTag_EnemyFlyingTag_CanHellpodAttachToTag_TwoHandedThrowableTag_AIObjectiveTargetTag_Value_100000_Len_28Tag_CanArcTag_NoTransportDeploymentTag_NoAimAssistTag_IgnoreEncounterCountTag_IgnoredByEnemiesTag_InvalidEnemyTargetTag_CanBeLockedOnTag_NoStatTrackingTag_SuitableMeleeTargetTag_Value_40000000_Len_29Tag_Value_80000000_Len_17Tag_Value_100000000_Len_28Tag_Value_200000000_Len_26Tag_Value_400000000_Len_22Tag_Value_800000000_Len_12Tag_Value_1000000000_Len_21Tag_Value_2000000000_Len_26Tag_Value_4000000000_Len_13Tag_Value_8000000000_Len_20"

var _Tag_map = map[Tag]string{
	0:            _Tag_name[0:8],
	1:            _Tag_name[8:21],
	2:            _Tag_name[21:34],
	4:            _Tag_name[34:48],
	8:            _Tag_name[48:68],
	16:           _Tag_name[68:88],
	32:           _Tag_name[88:115],
	64:           _Tag_name[115:128],
	128:          _Tag_name[128:139],
	256:          _Tag_name[139:154],
	512:          _Tag_name[154:163],
	2048:         _Tag_name[163:179],
	4096:         _Tag_name[179:189],
	8192:         _Tag_name[189:200],
	16384:        _Tag_name[200:209],
	32768:        _Tag_name[209:230],
	65536:        _Tag_name[230:245],
	131072:       _Tag_name[245:267],
	262144:       _Tag_name[267:289],
	524288:       _Tag_name[289:310],
	1048576:      _Tag_name[310:333],
	2097152:      _Tag_name[333:343],
	4194304:      _Tag_name[343:368],
	8388608:      _Tag_name[368:383],
	16777216:     _Tag_name[383:407],
	33554432:     _Tag_name[407:427],
	67108864:     _Tag_name[427:449],
	134217728:    _Tag_name[449:466],
	268435456:    _Tag_name[466:484],
	536870912:    _Tag_name[484:507],
	1073741824:   _Tag_name[507:532],
	2147483648:   _Tag_name[532:557],
	4294967296:   _Tag_name[557:583],
	8589934592:   _Tag_name[583:609],
	17179869184:  _Tag_name[609:635],
	34359738368:  _Tag_name[635:661],
	68719476736:  _Tag_name[661:688],
	137438953472: _Tag_name[688:715],
	274877906944: _Tag_name[715:742],
	549755813888: _Tag_name[742:769],
}

func (i Tag) String() string {
	if str, ok := _Tag_map[i]; ok {
		return str
	}
	return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
}
