// Code generated by "stringer -type=TaskUser"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskUser_None-0]
	_ = x[TaskUser_Value_1-1]
	_ = x[TaskUser_Value_2-2]
	_ = x[TaskUser_Value_4-4]
	_ = x[TaskUser_Value_8-8]
	_ = x[TaskUser_Value_10-16]
	_ = x[TaskUser_Value_20-32]
	_ = x[TaskUser_Value_40-64]
	_ = x[TaskUser_Value_80-128]
	_ = x[TaskUser_Value_100-256]
	_ = x[TaskUser_Value_200-512]
	_ = x[TaskUser_Value_800-2048]
	_ = x[TaskUser_Value_1000-4096]
	_ = x[TaskUser_Value_2000-8192]
	_ = x[TaskUser_Value_4000-16384]
	_ = x[TaskUser_Value_8000-32768]
	_ = x[TaskUser_Value_10000-65536]
	_ = x[TaskUser_Value_20000-131072]
	_ = x[TaskUser_Value_40000-262144]
}

const _TaskUser_name = "TaskUser_NoneTaskUser_Value_1TaskUser_Value_2TaskUser_Value_4TaskUser_Value_8TaskUser_Value_10TaskUser_Value_20TaskUser_Value_40TaskUser_Value_80TaskUser_Value_100TaskUser_Value_200TaskUser_Value_800TaskUser_Value_1000TaskUser_Value_2000TaskUser_Value_4000TaskUser_Value_8000TaskUser_Value_10000TaskUser_Value_20000TaskUser_Value_40000"

var _TaskUser_map = map[TaskUser]string{
	0:      _TaskUser_name[0:13],
	1:      _TaskUser_name[13:29],
	2:      _TaskUser_name[29:45],
	4:      _TaskUser_name[45:61],
	8:      _TaskUser_name[61:77],
	16:     _TaskUser_name[77:94],
	32:     _TaskUser_name[94:111],
	64:     _TaskUser_name[111:128],
	128:    _TaskUser_name[128:145],
	256:    _TaskUser_name[145:163],
	512:    _TaskUser_name[163:181],
	2048:   _TaskUser_name[181:199],
	4096:   _TaskUser_name[199:218],
	8192:   _TaskUser_name[218:237],
	16384:  _TaskUser_name[237:256],
	32768:  _TaskUser_name[256:275],
	65536:  _TaskUser_name[275:295],
	131072: _TaskUser_name[295:315],
	262144: _TaskUser_name[315:335],
}

func (i TaskUser) String() string {
	if str, ok := _TaskUser_map[i]; ok {
		return str
	}
	return "TaskUser(" + strconv.FormatInt(int64(i), 10) + ")"
}
