// Code generated by "stringer -type=TerrainDeformationType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TerrainDeformationType_None-0]
	_ = x[TerrainDeformationType_Default-1]
	_ = x[TerrainDeformationType_Nuke-2]
	_ = x[TerrainDeformationType_Large-3]
	_ = x[TerrainDeformationType_Medium-4]
	_ = x[TerrainDeformationType_Small-5]
	_ = x[TerrainDeformationType_Scorch-6]
	_ = x[TerrainDeformationType_FlattenHeightmapAO-7]
	_ = x[TerrainDeformationType_Value_8_Len_29-8]
	_ = x[TerrainDeformationType_Value_9_Len_43-9]
	_ = x[TerrainDeformationType_Value_10_Len_40-10]
	_ = x[TerrainDeformationType_Value_11_Len_44-11]
	_ = x[TerrainDeformationType_Value_12_Len_45-12]
	_ = x[TerrainDeformationType_Value_13_Len_44-13]
	_ = x[TerrainDeformationType_Count-14]
}

const _TerrainDeformationType_name = "TerrainDeformationType_NoneTerrainDeformationType_DefaultTerrainDeformationType_NukeTerrainDeformationType_LargeTerrainDeformationType_MediumTerrainDeformationType_SmallTerrainDeformationType_ScorchTerrainDeformationType_FlattenHeightmapAOTerrainDeformationType_Value_8_Len_29TerrainDeformationType_Value_9_Len_43TerrainDeformationType_Value_10_Len_40TerrainDeformationType_Value_11_Len_44TerrainDeformationType_Value_12_Len_45TerrainDeformationType_Value_13_Len_44TerrainDeformationType_Count"

var _TerrainDeformationType_index = [...]uint16{0, 27, 57, 84, 112, 141, 169, 198, 239, 276, 313, 351, 389, 427, 465, 493}

func (i TerrainDeformationType) String() string {
	if i >= TerrainDeformationType(len(_TerrainDeformationType_index)-1) {
		return "TerrainDeformationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TerrainDeformationType_name[_TerrainDeformationType_index[i]:_TerrainDeformationType_index[i+1]]
}
