// Code generated by "stringer -type=TextureType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TextureType_NoMask-0]
	_ = x[TextureType_ShadowMask-1]
	_ = x[TextureType_RgbMask-2]
}

const _TextureType_name = "TextureType_NoMaskTextureType_ShadowMaskTextureType_RgbMask"

var _TextureType_index = [...]uint8{0, 18, 40, 59}

func (i TextureType) String() string {
	if i >= TextureType(len(_TextureType_index)-1) {
		return "TextureType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TextureType_name[_TextureType_index[i]:_TextureType_index[i+1]]
}
