// Code generated by "stringer -type=UnitEffectOrphanStrategy"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrphanStrategyNone-0]
	_ = x[OrphanStrategyDestroy-1]
	_ = x[OrphanStrategyStop-2]
	_ = x[OrphanStrategyDisconnect-3]
}

const _UnitEffectOrphanStrategy_name = "OrphanStrategyNoneOrphanStrategyDestroyOrphanStrategyStopOrphanStrategyDisconnect"

var _UnitEffectOrphanStrategy_index = [...]uint8{0, 18, 39, 57, 81}

func (i UnitEffectOrphanStrategy) String() string {
	if i >= UnitEffectOrphanStrategy(len(_UnitEffectOrphanStrategy_index)-1) {
		return "UnitEffectOrphanStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitEffectOrphanStrategy_name[_UnitEffectOrphanStrategy_index[i]:_UnitEffectOrphanStrategy_index[i+1]]
}
