// Code generated by "stringer -type=UnitSize"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnitSize_Small-0]
	_ = x[UnitSize_Medium-1]
	_ = x[UnitSize_Large-2]
	_ = x[UnitSize_Massive-3]
	_ = x[UnitSize_Num-4]
}

const _UnitSize_name = "UnitSize_SmallUnitSize_MediumUnitSize_LargeUnitSize_MassiveUnitSize_Num"

var _UnitSize_index = [...]uint8{0, 14, 29, 43, 59, 71}

func (i UnitSize) String() string {
	if i >= UnitSize(len(_UnitSize_index)-1) {
		return "UnitSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitSize_name[_UnitSize_index[i]:_UnitSize_index[i+1]]
}
