// Code generated by "stringer -type=WeaponReloadEventType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponReloadEventType_None-0]
	_ = x[WeaponReloadEventType_ReloadNormal-1]
	_ = x[WeaponReloadEventType_ReloadNormalOneHand-2]
	_ = x[WeaponReloadEventType_ReloadFast-3]
	_ = x[WeaponReloadEventType_ReloadFastOneHand-4]
}

const _WeaponReloadEventType_name = "WeaponReloadEventType_NoneWeaponReloadEventType_ReloadNormalWeaponReloadEventType_ReloadNormalOneHandWeaponReloadEventType_ReloadFastWeaponReloadEventType_ReloadFastOneHand"

var _WeaponReloadEventType_index = [...]uint8{0, 26, 60, 101, 133, 172}

func (i WeaponReloadEventType) String() string {
	if i >= WeaponReloadEventType(len(_WeaponReloadEventType_index)-1) {
		return "WeaponReloadEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponReloadEventType_name[_WeaponReloadEventType_index[i]:_WeaponReloadEventType_index[i+1]]
}
