// Code generated by "stringer -type=WeaponCustomizationSlot"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponCustomizationSlot_None-0]
	_ = x[WeaponCustomizationSlot_Underbarrel-1]
	_ = x[WeaponCustomizationSlot_Optics-2]
	_ = x[WeaponCustomizationSlot_PaintScheme-3]
	_ = x[WeaponCustomizationSlot_Muzzle-4]
	_ = x[WeaponCustomizationSlot_Magazine-5]
	_ = x[WeaponCustomizationSlot_AmmoType-6]
	_ = x[WeaponCustomizationSlot_AmmoTypeAlternate-7]
	_ = x[WeaponCustomizationSlot_Internals-8]
	_ = x[WeaponCustomizationSlot_Triggers-9]
	_ = x[WeaponCustomizationSlot_Count-10]
}

const _WeaponCustomizationSlot_name = "WeaponCustomizationSlot_NoneWeaponCustomizationSlot_UnderbarrelWeaponCustomizationSlot_OpticsWeaponCustomizationSlot_PaintSchemeWeaponCustomizationSlot_MuzzleWeaponCustomizationSlot_MagazineWeaponCustomizationSlot_AmmoTypeWeaponCustomizationSlot_AmmoTypeAlternateWeaponCustomizationSlot_InternalsWeaponCustomizationSlot_TriggersWeaponCustomizationSlot_Count"

var _WeaponCustomizationSlot_index = [...]uint16{0, 28, 63, 93, 128, 158, 190, 222, 263, 296, 328, 357}

func (i WeaponCustomizationSlot) String() string {
	if i >= WeaponCustomizationSlot(len(_WeaponCustomizationSlot_index)-1) {
		return "WeaponCustomizationSlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponCustomizationSlot_name[_WeaponCustomizationSlot_index[i]:_WeaponCustomizationSlot_index[i+1]]
}
