// Code generated by "stringer -type=WeaponStatModifierType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponStatModifierType_Add_Ergonomics-0]
	_ = x[WeaponStatModifierType_Mul_Sway-1]
	_ = x[WeaponStatModifierType_Mul_RecoilHorizontal-2]
	_ = x[WeaponStatModifierType_Mul_RecoilHorizontalAlt-3]
	_ = x[WeaponStatModifierType_Mul_RecoilVertical-4]
	_ = x[WeaponStatModifierType_Mul_RecoilVerticalAlt-5]
	_ = x[WeaponStatModifierType_Mul_DriftHorizontal-6]
	_ = x[WeaponStatModifierType_Mul_DriftHorizontalAlt-7]
	_ = x[WeaponStatModifierType_Mul_DriftVertical-8]
	_ = x[WeaponStatModifierType_Mul_DriftVerticalAlt-9]
	_ = x[WeaponStatModifierType_Mul_ClimbHorizontal-10]
	_ = x[WeaponStatModifierType_Mul_ClimbHorizontalAlt-11]
	_ = x[WeaponStatModifierType_Mul_ClimbVertical-12]
	_ = x[WeaponStatModifierType_Mul_ClimbVerticalAlt-13]
	_ = x[WeaponStatModifierType_Mul_SpreadHorizontal-14]
	_ = x[WeaponStatModifierType_Mul_SpreadHorizontalAlt-15]
	_ = x[WeaponStatModifierType_Mul_SpreadVertical-16]
	_ = x[WeaponStatModifierType_Mul_SpreadVerticalAlt-17]
	_ = x[WeaponStatModifierType_Count-18]
}

const _WeaponStatModifierType_name = "WeaponStatModifierType_Add_ErgonomicsWeaponStatModifierType_Mul_SwayWeaponStatModifierType_Mul_RecoilHorizontalWeaponStatModifierType_Mul_RecoilHorizontalAltWeaponStatModifierType_Mul_RecoilVerticalWeaponStatModifierType_Mul_RecoilVerticalAltWeaponStatModifierType_Mul_DriftHorizontalWeaponStatModifierType_Mul_DriftHorizontalAltWeaponStatModifierType_Mul_DriftVerticalWeaponStatModifierType_Mul_DriftVerticalAltWeaponStatModifierType_Mul_ClimbHorizontalWeaponStatModifierType_Mul_ClimbHorizontalAltWeaponStatModifierType_Mul_ClimbVerticalWeaponStatModifierType_Mul_ClimbVerticalAltWeaponStatModifierType_Mul_SpreadHorizontalWeaponStatModifierType_Mul_SpreadHorizontalAltWeaponStatModifierType_Mul_SpreadVerticalWeaponStatModifierType_Mul_SpreadVerticalAltWeaponStatModifierType_Count"

var _WeaponStatModifierType_index = [...]uint16{0, 37, 68, 111, 157, 198, 242, 284, 329, 369, 412, 454, 499, 539, 582, 625, 671, 712, 756, 784}

func (i WeaponStatModifierType) String() string {
	if i >= WeaponStatModifierType(len(_WeaponStatModifierType_index)-1) {
		return "WeaponStatModifierType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponStatModifierType_name[_WeaponStatModifierType_index[i]:_WeaponStatModifierType_index[i+1]]
}
