// Code generated by "stringer -type=WeaponGripType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponGripType_Unarmed-0]
	_ = x[WeaponGripType_Pistol-1]
	_ = x[WeaponGripType_ShotgunPistol-5]
	_ = x[WeaponGripType_Revolver-9]
	_ = x[WeaponGripType_Rifle-10]
	_ = x[WeaponGripType_PlasmaRifle-14]
	_ = x[WeaponGripType_MarksmanRifle-15]
	_ = x[WeaponGripType_ShoulderMounted-20]
	_ = x[WeaponGripType_LAT-21]
	_ = x[WeaponGripType_Autocannon-22]
	_ = x[WeaponGripType_CarryOneHanded-30]
	_ = x[WeaponGripType_CarryShield-36]
	_ = x[WeaponGripType_Grenade-40]
	_ = x[WeaponGripType_FragGrenade-41]
	_ = x[WeaponGripType_StickyGrenade-42]
	_ = x[WeaponGripType_Machinegun-50]
	_ = x[WeaponGripType_Grenadelauncher-51]
	_ = x[WeaponGripType_Sniperrifle-52]
	_ = x[WeaponGripType_Flamethrower-60]
	_ = x[WeaponGripType_Railgun-61]
	_ = x[WeaponGripType_PDW-70]
	_ = x[WeaponGripType_PumpShotgun-80]
	_ = x[WeaponGripType_RifleBullpup-90]
}

const _WeaponGripType_name = "WeaponGripType_UnarmedWeaponGripType_PistolWeaponGripType_ShotgunPistolWeaponGripType_RevolverWeaponGripType_RifleWeaponGripType_PlasmaRifleWeaponGripType_MarksmanRifleWeaponGripType_ShoulderMountedWeaponGripType_LATWeaponGripType_AutocannonWeaponGripType_CarryOneHandedWeaponGripType_CarryShieldWeaponGripType_GrenadeWeaponGripType_FragGrenadeWeaponGripType_StickyGrenadeWeaponGripType_MachinegunWeaponGripType_GrenadelauncherWeaponGripType_SniperrifleWeaponGripType_FlamethrowerWeaponGripType_RailgunWeaponGripType_PDWWeaponGripType_PumpShotgunWeaponGripType_RifleBullpup"

var _WeaponGripType_map = map[WeaponGripType]string{
	0:  _WeaponGripType_name[0:22],
	1:  _WeaponGripType_name[22:43],
	5:  _WeaponGripType_name[43:71],
	9:  _WeaponGripType_name[71:94],
	10: _WeaponGripType_name[94:114],
	14: _WeaponGripType_name[114:140],
	15: _WeaponGripType_name[140:168],
	20: _WeaponGripType_name[168:198],
	21: _WeaponGripType_name[198:216],
	22: _WeaponGripType_name[216:241],
	30: _WeaponGripType_name[241:270],
	36: _WeaponGripType_name[270:296],
	40: _WeaponGripType_name[296:318],
	41: _WeaponGripType_name[318:344],
	42: _WeaponGripType_name[344:372],
	50: _WeaponGripType_name[372:397],
	51: _WeaponGripType_name[397:427],
	52: _WeaponGripType_name[427:453],
	60: _WeaponGripType_name[453:480],
	61: _WeaponGripType_name[480:502],
	70: _WeaponGripType_name[502:520],
	80: _WeaponGripType_name[520:546],
	90: _WeaponGripType_name[546:573],
}

func (i WeaponGripType) String() string {
	if str, ok := _WeaponGripType_map[i]; ok {
		return str
	}
	return "WeaponGripType(" + strconv.FormatInt(int64(i), 10) + ")"
}
