// Code generated by "stringer -type=WeaponLinkedAmmoMode"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponLinkedAmmoMode_Value_0_Len_33-0]
	_ = x[WeaponLinkedAmmoMode_Value_1_Len_34-1]
	_ = x[WeaponLinkedAmmoMode_Value_2_Len_27-2]
}

const _WeaponLinkedAmmoMode_name = "WeaponLinkedAmmoMode_Value_0_Len_33WeaponLinkedAmmoMode_Value_1_Len_34WeaponLinkedAmmoMode_Value_2_Len_27"

var _WeaponLinkedAmmoMode_index = [...]uint8{0, 35, 70, 105}

func (i WeaponLinkedAmmoMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WeaponLinkedAmmoMode_index)-1 {
		return "WeaponLinkedAmmoMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponLinkedAmmoMode_name[_WeaponLinkedAmmoMode_index[idx]:_WeaponLinkedAmmoMode_index[idx+1]]
}
