// Code generated by "stringer -type=WeatherType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeatherType_NoWeather-0]
	_ = x[WeatherType_Clear-1]
	_ = x[WeatherType_Cloudy-2]
	_ = x[WeatherType_Value_3_Len_17-3]
	_ = x[WeatherType_Raining-4]
	_ = x[WeatherType_Value_5_Len_17-5]
	_ = x[WeatherType_Value_6_Len_21-6]
	_ = x[WeatherType_Value_7_Len_21-7]
	_ = x[WeatherType_Value_8_Len_21-8]
	_ = x[WeatherType_Value_9_Len_21-9]
}

const _WeatherType_name = "WeatherType_NoWeatherWeatherType_ClearWeatherType_CloudyWeatherType_Value_3_Len_17WeatherType_RainingWeatherType_Value_5_Len_17WeatherType_Value_6_Len_21WeatherType_Value_7_Len_21WeatherType_Value_8_Len_21WeatherType_Value_9_Len_21"

var _WeatherType_index = [...]uint8{0, 21, 38, 56, 82, 101, 127, 153, 179, 205, 231}

func (i WeatherType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WeatherType_index)-1 {
		return "WeatherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeatherType_name[_WeatherType_index[idx]:_WeatherType_index[idx+1]]
}
