// Code generated by "stringer -type=ZoneFogColorGroups"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZoneFogColorGroups_None-0]
	_ = x[ZoneFogColorGroups_Main-1]
	_ = x[ZoneFogColorGroups_Secondary-2]
	_ = x[ZoneFogColorGroups_Bugs-3]
	_ = x[ZoneFogColorGroups_Bots-4]
	_ = x[ZoneFogColorGroups_Illuminate-5]
}

const _ZoneFogColorGroups_name = "ZoneFogColorGroups_NoneZoneFogColorGroups_MainZoneFogColorGroups_SecondaryZoneFogColorGroups_BugsZoneFogColorGroups_BotsZoneFogColorGroups_Illuminate"

var _ZoneFogColorGroups_index = [...]uint8{0, 23, 46, 74, 97, 120, 149}

func (i ZoneFogColorGroups) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ZoneFogColorGroups_index)-1 {
		return "ZoneFogColorGroups(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoneFogColorGroups_name[_ZoneFogColorGroups_index[idx]:_ZoneFogColorGroups_index[idx+1]]
}
