// Code generated by "stringer -type=ZoneId"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZONE_ID_UNKNOWN-0]
	_ = x[ZoneId_Value_1_Len_25-1]
	_ = x[ZoneId_Value_2_Len_33-2]
	_ = x[ZoneId_Value_3_Len_23-3]
	_ = x[ZoneId_Value_4_Len_31-4]
	_ = x[ZoneId_Value_5_Len_35-5]
	_ = x[ZoneId_Value_6_Len_38-6]
	_ = x[ZoneId_Value_7_Len_41-7]
	_ = x[ZoneId_Value_8_Len_45-8]
	_ = x[ZoneId_Value_9_Len_48-9]
	_ = x[ZoneId_Value_10_Len_52-10]
	_ = x[ZoneId_Value_11_Len_42-11]
	_ = x[ZoneId_Value_12_Len_29-12]
	_ = x[ZoneId_Value_13_Len_40-13]
	_ = x[ZoneId_Value_14_Len_39-14]
	_ = x[ZoneId_Value_15_Len_39-15]
	_ = x[ZoneId_Value_16_Len_37-16]
	_ = x[ZoneId_Value_17_Len_39-17]
	_ = x[ZoneId_Value_18_Len_38-18]
	_ = x[ZoneId_Value_19_Len_37-19]
	_ = x[ZoneId_Value_20_Len_29-20]
	_ = x[ZoneId_Value_21_Len_39-21]
	_ = x[ZoneId_Value_22_Len_36-22]
	_ = x[ZoneId_Value_23_Len_39-23]
	_ = x[ZoneId_Value_24_Len_43-24]
	_ = x[ZoneId_Value_25_Len_29-25]
	_ = x[ZoneId_Value_26_Len_40-26]
	_ = x[ZoneId_Value_27_Len_27-27]
	_ = x[ZoneId_Value_28_Len_29-28]
	_ = x[ZoneId_Value_29_Len_30-29]
	_ = x[ZoneId_Value_30_Len_39-30]
	_ = x[ZoneId_Value_31_Len_36-31]
	_ = x[ZoneId_Value_32_Len_40-32]
	_ = x[ZoneId_Value_33_Len_37-33]
	_ = x[ZoneId_Value_34_Len_45-34]
	_ = x[ZoneId_Value_35_Len_37-35]
	_ = x[ZoneId_Value_36_Len_33-36]
	_ = x[ZoneId_Value_37_Len_27-37]
	_ = x[ZoneId_Value_38_Len_28-38]
	_ = x[ZoneId_Value_39_Len_31-39]
	_ = x[ZoneId_Value_40_Len_36-40]
	_ = x[ZoneId_Value_41_Len_36-41]
	_ = x[ZoneId_Value_42_Len_34-42]
	_ = x[ZoneId_Value_43_Len_32-43]
	_ = x[ZoneId_Value_44_Len_24-44]
	_ = x[ZoneId_Value_45_Len_23-45]
	_ = x[ZoneId_Value_46_Len_28-46]
	_ = x[ZoneId_Value_47_Len_24-47]
	_ = x[ZoneId_Value_48_Len_31-48]
	_ = x[ZoneId_Value_49_Len_24-49]
	_ = x[ZoneId_Value_50_Len_39-50]
	_ = x[ZoneId_Value_51_Len_24-51]
	_ = x[ZoneId_Value_52_Len_27-52]
	_ = x[ZoneId_Value_53_Len_47-53]
	_ = x[ZoneId_Value_54_Len_44-54]
	_ = x[ZoneId_Value_55_Len_36-55]
	_ = x[ZoneId_Value_56_Len_36-56]
	_ = x[ZoneId_Value_57_Len_42-57]
	_ = x[ZoneId_Value_58_Len_47-58]
	_ = x[ZoneId_Value_59_Len_36-59]
	_ = x[ZoneId_Value_60_Len_38-60]
	_ = x[ZoneId_Value_61_Len_35-61]
	_ = x[ZoneId_Value_62_Len_35-62]
	_ = x[ZoneId_Value_63_Len_28-63]
	_ = x[ZoneId_Value_64_Len_39-64]
	_ = x[ZoneId_Value_65_Len_30-65]
	_ = x[ZoneId_Value_66_Len_33-66]
	_ = x[ZoneId_Value_67_Len_41-67]
	_ = x[ZoneId_Value_68_Len_32-68]
	_ = x[ZoneId_Value_69_Len_30-69]
	_ = x[ZoneId_Value_70_Len_38-70]
	_ = x[ZoneId_Value_71_Len_29-71]
	_ = x[ZoneId_Value_72_Len_28-72]
	_ = x[ZoneId_Value_73_Len_30-73]
	_ = x[ZoneId_Value_74_Len_29-74]
	_ = x[ZoneId_Value_75_Len_29-75]
	_ = x[ZoneId_Value_76_Len_37-76]
	_ = x[ZoneId_Value_77_Len_31-77]
	_ = x[ZoneId_Value_78_Len_33-78]
	_ = x[ZoneId_Value_79_Len_32-79]
	_ = x[ZoneId_Value_80_Len_30-80]
	_ = x[ZoneId_Value_81_Len_35-81]
	_ = x[ZoneId_Value_82_Len_24-82]
	_ = x[ZoneId_Value_83_Len_26-83]
	_ = x[ZoneId_Value_84_Len_31-84]
	_ = x[ZoneId_Value_85_Len_27-85]
	_ = x[ZoneId_Value_86_Len_25-86]
	_ = x[ZoneId_Value_87_Len_23-87]
	_ = x[ZONE_ID_wall_stamps-88]
	_ = x[ZONE_ID_NUM_ZONES-89]
}

const _ZoneId_name = "ZONE_ID_UNKNOWNZoneId_Value_1_Len_25ZoneId_Value_2_Len_33ZoneId_Value_3_Len_23ZoneId_Value_4_Len_31ZoneId_Value_5_Len_35ZoneId_Value_6_Len_38ZoneId_Value_7_Len_41ZoneId_Value_8_Len_45ZoneId_Value_9_Len_48ZoneId_Value_10_Len_52ZoneId_Value_11_Len_42ZoneId_Value_12_Len_29ZoneId_Value_13_Len_40ZoneId_Value_14_Len_39ZoneId_Value_15_Len_39ZoneId_Value_16_Len_37ZoneId_Value_17_Len_39ZoneId_Value_18_Len_38ZoneId_Value_19_Len_37ZoneId_Value_20_Len_29ZoneId_Value_21_Len_39ZoneId_Value_22_Len_36ZoneId_Value_23_Len_39ZoneId_Value_24_Len_43ZoneId_Value_25_Len_29ZoneId_Value_26_Len_40ZoneId_Value_27_Len_27ZoneId_Value_28_Len_29ZoneId_Value_29_Len_30ZoneId_Value_30_Len_39ZoneId_Value_31_Len_36ZoneId_Value_32_Len_40ZoneId_Value_33_Len_37ZoneId_Value_34_Len_45ZoneId_Value_35_Len_37ZoneId_Value_36_Len_33ZoneId_Value_37_Len_27ZoneId_Value_38_Len_28ZoneId_Value_39_Len_31ZoneId_Value_40_Len_36ZoneId_Value_41_Len_36ZoneId_Value_42_Len_34ZoneId_Value_43_Len_32ZoneId_Value_44_Len_24ZoneId_Value_45_Len_23ZoneId_Value_46_Len_28ZoneId_Value_47_Len_24ZoneId_Value_48_Len_31ZoneId_Value_49_Len_24ZoneId_Value_50_Len_39ZoneId_Value_51_Len_24ZoneId_Value_52_Len_27ZoneId_Value_53_Len_47ZoneId_Value_54_Len_44ZoneId_Value_55_Len_36ZoneId_Value_56_Len_36ZoneId_Value_57_Len_42ZoneId_Value_58_Len_47ZoneId_Value_59_Len_36ZoneId_Value_60_Len_38ZoneId_Value_61_Len_35ZoneId_Value_62_Len_35ZoneId_Value_63_Len_28ZoneId_Value_64_Len_39ZoneId_Value_65_Len_30ZoneId_Value_66_Len_33ZoneId_Value_67_Len_41ZoneId_Value_68_Len_32ZoneId_Value_69_Len_30ZoneId_Value_70_Len_38ZoneId_Value_71_Len_29ZoneId_Value_72_Len_28ZoneId_Value_73_Len_30ZoneId_Value_74_Len_29ZoneId_Value_75_Len_29ZoneId_Value_76_Len_37ZoneId_Value_77_Len_31ZoneId_Value_78_Len_33ZoneId_Value_79_Len_32ZoneId_Value_80_Len_30ZoneId_Value_81_Len_35ZoneId_Value_82_Len_24ZoneId_Value_83_Len_26ZoneId_Value_84_Len_31ZoneId_Value_85_Len_27ZoneId_Value_86_Len_25ZoneId_Value_87_Len_23ZONE_ID_wall_stampsZONE_ID_NUM_ZONES"

var _ZoneId_index = [...]uint16{0, 15, 36, 57, 78, 99, 120, 141, 162, 183, 204, 226, 248, 270, 292, 314, 336, 358, 380, 402, 424, 446, 468, 490, 512, 534, 556, 578, 600, 622, 644, 666, 688, 710, 732, 754, 776, 798, 820, 842, 864, 886, 908, 930, 952, 974, 996, 1018, 1040, 1062, 1084, 1106, 1128, 1150, 1172, 1194, 1216, 1238, 1260, 1282, 1304, 1326, 1348, 1370, 1392, 1414, 1436, 1458, 1480, 1502, 1524, 1546, 1568, 1590, 1612, 1634, 1656, 1678, 1700, 1722, 1744, 1766, 1788, 1810, 1832, 1854, 1876, 1898, 1920, 1939, 1956}

func (i ZoneId) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ZoneId_index)-1 {
		return "ZoneId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoneId_name[_ZoneId_index[idx]:_ZoneId_index[idx+1]]
}
