// Code generated by "stringer -type=ZoneTag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZoneTag_None-0]
	_ = x[ZoneTag_Value_1_Len_14-1]
	_ = x[ZoneTag_Value_2_Len_14-2]
	_ = x[ZoneTag_Value_3_Len_12-3]
	_ = x[ZoneTag_Value_4_Len_15-4]
	_ = x[ZoneTag_Value_5_Len_12-5]
	_ = x[ZoneTag_Value_6_Len_11-6]
	_ = x[ZoneTag_Value_7_Len_11-7]
	_ = x[ZoneTag_Value_8_Len_18-8]
	_ = x[ZoneTag_Value_9_Len_13-9]
	_ = x[ZoneTag_Value_10_Len_16-10]
	_ = x[ZoneTag_Value_11_Len_14-11]
	_ = x[ZoneTag_Value_12_Len_14-12]
	_ = x[ZoneTag_Value_13_Len_13-13]
	_ = x[ZoneTag_Value_14_Len_21-14]
	_ = x[ZoneTag_Value_15_Len_18-15]
	_ = x[ZoneTag_Value_16_Len_15-16]
	_ = x[ZoneTag_Value_17_Len_34-17]
	_ = x[ZoneTag_Count-18]
}

const _ZoneTag_name = "ZoneTag_NoneZoneTag_Value_1_Len_14ZoneTag_Value_2_Len_14ZoneTag_Value_3_Len_12ZoneTag_Value_4_Len_15ZoneTag_Value_5_Len_12ZoneTag_Value_6_Len_11ZoneTag_Value_7_Len_11ZoneTag_Value_8_Len_18ZoneTag_Value_9_Len_13ZoneTag_Value_10_Len_16ZoneTag_Value_11_Len_14ZoneTag_Value_12_Len_14ZoneTag_Value_13_Len_13ZoneTag_Value_14_Len_21ZoneTag_Value_15_Len_18ZoneTag_Value_16_Len_15ZoneTag_Value_17_Len_34ZoneTag_Count"

var _ZoneTag_index = [...]uint16{0, 12, 34, 56, 78, 100, 122, 144, 166, 188, 210, 233, 256, 279, 302, 325, 348, 371, 394, 407}

func (i ZoneTag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ZoneTag_index)-1 {
		return "ZoneTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoneTag_name[_ZoneTag_index[idx]:_ZoneTag_index[idx+1]]
}
