// Code generated by "stringer -type=ZoneMusicType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZoneMusicType_None-0]
	_ = x[ZoneMusicType_Bug-1]
}

const _ZoneMusicType_name = "ZoneMusicType_NoneZoneMusicType_Bug"

var _ZoneMusicType_index = [...]uint8{0, 18, 35}

func (i ZoneMusicType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ZoneMusicType_index)-1 {
		return "ZoneMusicType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoneMusicType_name[_ZoneMusicType_index[idx]:_ZoneMusicType_index[idx+1]]
}
