// Code generated by "stringer -type=GradingType"; DO NOT EDIT.

package asset_grading

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Hue-1]
	_ = x[Saturation-2]
	_ = x[Value-3]
	_ = x[Contrast-4]
	_ = x[ContrastMidpoint-5]
	_ = x[Color-6]
}

const _GradingType_name = "NoneHueSaturationValueContrastContrastMidpointColor"

var _GradingType_index = [...]uint8{0, 4, 7, 17, 22, 30, 46, 51}

func (i GradingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GradingType_index)-1 {
		return "GradingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GradingType_name[_GradingType_index[idx]:_GradingType_index[idx+1]]
}
