// Code generated by "stringer -type=GLError"; DO NOT EDIT.

package glutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GL_NO_ERROR-0]
	_ = x[GL_INVALID_ENUM-1280]
	_ = x[GL_INVALID_VALUE-1281]
	_ = x[GL_INVALID_OPERATION-1282]
	_ = x[GL_INVALID_FRAMEBUFFER_OPERATION-1286]
	_ = x[GL_OUT_OF_MEMORY-1285]
	_ = x[GL_STACK_UNDERFLOW-1284]
	_ = x[GL_STACK_OVERFLOW-1283]
}

const (
	_GLError_name_0 = "GL_NO_ERROR"
	_GLError_name_1 = "GL_INVALID_ENUMGL_INVALID_VALUEGL_INVALID_OPERATIONGL_STACK_OVERFLOWGL_STACK_UNDERFLOWGL_OUT_OF_MEMORYGL_INVALID_FRAMEBUFFER_OPERATION"
)

var (
	_GLError_index_1 = [...]uint8{0, 15, 31, 51, 68, 86, 102, 134}
)

func (i GLError) String() string {
	switch {
	case i == 0:
		return _GLError_name_0
	case 1280 <= i && i <= 1286:
		i -= 1280
		return _GLError_name_1[_GLError_index_1[i]:_GLError_index_1[i+1]]
	default:
		return "GLError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
