// Code generated by "stringer -type=GLTarget"; DO NOT EDIT.

package glutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GL_TEXTURE_1D-3552]
	_ = x[GL_TEXTURE_2D-3553]
	_ = x[GL_TEXTURE_3D-32879]
	_ = x[GL_TEXTURE_1D_ARRAY-35864]
	_ = x[GL_TEXTURE_2D_ARRAY-35866]
	_ = x[GL_TEXTURE_CUBE_MAP-34067]
	_ = x[GL_TEXTURE_CUBE_MAP_ARRAY-36873]
	_ = x[GL_TEXTURE_BUFFER-35882]
}

const (
	_GLTarget_name_0 = "GL_TEXTURE_1DGL_TEXTURE_2D"
	_GLTarget_name_1 = "GL_TEXTURE_3D"
	_GLTarget_name_2 = "GL_TEXTURE_CUBE_MAP"
	_GLTarget_name_3 = "GL_TEXTURE_1D_ARRAY"
	_GLTarget_name_4 = "GL_TEXTURE_2D_ARRAY"
	_GLTarget_name_5 = "GL_TEXTURE_BUFFER"
	_GLTarget_name_6 = "GL_TEXTURE_CUBE_MAP_ARRAY"
)

var (
	_GLTarget_index_0 = [...]uint8{0, 13, 26}
)

func (i GLTarget) String() string {
	switch {
	case 3552 <= i && i <= 3553:
		i -= 3552
		return _GLTarget_name_0[_GLTarget_index_0[i]:_GLTarget_index_0[i+1]]
	case i == 32879:
		return _GLTarget_name_1
	case i == 34067:
		return _GLTarget_name_2
	case i == 35864:
		return _GLTarget_name_3
	case i == 35866:
		return _GLTarget_name_4
	case i == 35882:
		return _GLTarget_name_5
	case i == 36873:
		return _GLTarget_name_6
	default:
		return "GLTarget(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
