// Code generated by "stringer -type=GLType"; DO NOT EDIT.

package glutils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GL_BOOL-35670]
	_ = x[GL_BYTE-5120]
	_ = x[GL_UNSIGNED_BYTE-5121]
	_ = x[GL_SHORT-5122]
	_ = x[GL_UNSIGNED_SHORT-5123]
	_ = x[GL_INT-5124]
	_ = x[GL_UNSIGNED_INT-5125]
	_ = x[GL_FIXED-5132]
	_ = x[GL_HALF_FLOAT-5131]
	_ = x[GL_FLOAT-5126]
	_ = x[GL_FLOAT_VEC2-35664]
	_ = x[GL_FLOAT_VEC3-35665]
	_ = x[GL_FLOAT_VEC4-35666]
	_ = x[GL_DOUBLE-5130]
}

const (
	_GLType_name_0 = "GL_BYTEGL_UNSIGNED_BYTEGL_SHORTGL_UNSIGNED_SHORTGL_INTGL_UNSIGNED_INTGL_FLOAT"
	_GLType_name_1 = "GL_DOUBLEGL_HALF_FLOATGL_FIXED"
	_GLType_name_2 = "GL_FLOAT_VEC2GL_FLOAT_VEC3GL_FLOAT_VEC4"
	_GLType_name_3 = "GL_BOOL"
)

var (
	_GLType_index_0 = [...]uint8{0, 7, 23, 31, 48, 54, 69, 77}
	_GLType_index_1 = [...]uint8{0, 9, 22, 30}
	_GLType_index_2 = [...]uint8{0, 13, 26, 39}
)

func (i GLType) String() string {
	switch {
	case 5120 <= i && i <= 5126:
		i -= 5120
		return _GLType_name_0[_GLType_index_0[i]:_GLType_index_0[i+1]]
	case 5130 <= i && i <= 5132:
		i -= 5130
		return _GLType_name_1[_GLType_index_1[i]:_GLType_index_1[i+1]]
	case 35664 <= i && i <= 35666:
		i -= 35664
		return _GLType_name_2[_GLType_index_2[i]:_GLType_index_2[i+1]]
	case i == 35670:
		return _GLType_name_3
	default:
		return "GLType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
