// Code generated by "stringer -type=SettingType"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SettingType_Unknown-0]
	_ = x[SettingType_U32-1]
	_ = x[SettingType_F32-2]
	_ = x[SettingType_String-3]
	_ = x[SettingType_Vector-4]
}

const _SettingType_name = "SettingType_UnknownSettingType_U32SettingType_F32SettingType_StringSettingType_Vector"

var _SettingType_index = [...]uint8{0, 19, 34, 49, 67, 85}

func (i SettingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SettingType_index)-1 {
		return "SettingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SettingType_name[_SettingType_index[idx]:_SettingType_index[idx+1]]
}
