// Code generated by "stringer -type=BeamType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BeamType_None-0]
	_ = x[BeamType_LaserCannon-1]
	_ = x[BeamType_BotTorch-2]
	_ = x[BeamType_Medium_Focused-3]
	_ = x[BeamType_Medium_Wide-4]
	_ = x[BeamType_Medium-5]
	_ = x[BeamType_ObserverEye-6]
	_ = x[BeamType_LaserCannon_Turret-7]
	_ = x[BeamType_Small-8]
	_ = x[BeamType_TripodEye-9]
	_ = x[BeamType_PhysGun-10]
	_ = x[BeamType_Unknown_Len_6-11]
	_ = x[BeamType_Large_Heavy-12]
	_ = x[BeamType_Large_Light-13]
	_ = x[BeamType_Large_Focused-14]
	_ = x[BeamType_Large_Unfocused-15]
	_ = x[BeamType_Large-16]
	_ = x[BeamType_Unknown_Len_11-17]
	_ = x[BeamType_Unknown_Len_15-18]
	_ = x[BeamType_OutcastFlashbeamChargeup-19]
	_ = x[BeamType_Unknown_Len_14-20]
	_ = x[BeamType_Count-21]
}

const _BeamType_name = "BeamType_NoneBeamType_LaserCannonBeamType_BotTorchBeamType_Medium_FocusedBeamType_Medium_WideBeamType_MediumBeamType_ObserverEyeBeamType_LaserCannon_TurretBeamType_SmallBeamType_TripodEyeBeamType_PhysGunBeamType_Unknown_Len_6BeamType_Large_HeavyBeamType_Large_LightBeamType_Large_FocusedBeamType_Large_UnfocusedBeamType_LargeBeamType_Unknown_Len_11BeamType_Unknown_Len_15BeamType_OutcastFlashbeamChargeupBeamType_Unknown_Len_14BeamType_Count"

var _BeamType_index = [...]uint16{0, 13, 33, 50, 73, 93, 108, 128, 155, 169, 187, 203, 225, 245, 265, 287, 311, 325, 348, 371, 404, 427, 441}

func (i BeamType) String() string {
	if i >= BeamType(len(_BeamType_index)-1) {
		return "BeamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BeamType_name[_BeamType_index[i]:_BeamType_index[i+1]]
}
