// Code generated by "stringer -type=ChargeState"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChargeState_MinCharge-0]
	_ = x[ChargeState_FullCharge-1]
	_ = x[ChargeState_OverCharge-2]
	_ = x[ChargeState_Count-3]
}

const _ChargeState_name = "ChargeState_MinChargeChargeState_FullChargeChargeState_OverChargeChargeState_Count"

var _ChargeState_index = [...]uint8{0, 21, 43, 65, 82}

func (i ChargeState) String() string {
	if i >= ChargeState(len(_ChargeState_index)-1) {
		return "ChargeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChargeState_name[_ChargeState_index[i]:_ChargeState_index[i+1]]
}
