// Code generated by "stringer -type=DLTypeAtom"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POD-0]
	_ = x[ARRAY-1]
	_ = x[INLINE_ARRAY-2]
	_ = x[BITFIELD-3]
	_ = x[ATOM_CNT-4]
}

const _DLTypeAtom_name = "PODARRAYINLINE_ARRAYBITFIELDATOM_CNT"

var _DLTypeAtom_index = [...]uint8{0, 3, 8, 20, 28, 36}

func (i DLTypeAtom) String() string {
	if i >= DLTypeAtom(len(_DLTypeAtom_index)-1) {
		return "DLTypeAtom(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DLTypeAtom_name[_DLTypeAtom_index[i]:_DLTypeAtom_index[i+1]]
}
