// Code generated by "stringer -type=FireMode"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FireMode_None-0]
	_ = x[FireMode_Automatic-1]
	_ = x[FireMode_Single-2]
	_ = x[FireMode_Burst-3]
	_ = x[FireMode_Safety_Off-4]
	_ = x[FireMode_Charge_Safety_On-5]
	_ = x[FireMode_Charge_Safety_Off-6]
	_ = x[FireMode_Safety_On-7]
	_ = x[FireMode_Count-8]
}

const _FireMode_name = "FireMode_NoneFireMode_AutomaticFireMode_SingleFireMode_BurstFireMode_Safety_OffFireMode_Charge_Safety_OnFireMode_Charge_Safety_OffFireMode_Safety_OnFireMode_Count"

var _FireMode_index = [...]uint8{0, 13, 31, 46, 60, 79, 104, 130, 148, 162}

func (i FireMode) String() string {
	if i >= FireMode(len(_FireMode_index)-1) {
		return "FireMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FireMode_name[_FireMode_index[i]:_FireMode_index[i+1]]
}
