// Code generated by "stringer -type=HelldiverCustomizationPassiveBonusModifierType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModifierTypeSet-0]
	_ = x[ModifierTypeAdd-1]
	_ = x[ModifierTypeMultiply-2]
	_ = x[ModifierTypeTime-3]
}

const _HelldiverCustomizationPassiveBonusModifierType_name = "ModifierTypeSetModifierTypeAddModifierTypeMultiplyModifierTypeTime"

var _HelldiverCustomizationPassiveBonusModifierType_index = [...]uint8{0, 15, 30, 50, 66}

func (i HelldiverCustomizationPassiveBonusModifierType) String() string {
	if i >= HelldiverCustomizationPassiveBonusModifierType(len(_HelldiverCustomizationPassiveBonusModifierType_index)-1) {
		return "HelldiverCustomizationPassiveBonusModifierType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HelldiverCustomizationPassiveBonusModifierType_name[_HelldiverCustomizationPassiveBonusModifierType_index[i]:_HelldiverCustomizationPassiveBonusModifierType_index[i+1]]
}
