// Code generated by "stringer -type=NoiseTemplate"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoiseTemplate_None-0]
	_ = x[NoiseTemplate_Toot-1]
	_ = x[NoiseTemplate_Engine-2]
	_ = x[NoiseTemplate_EnemyWarning-3]
	_ = x[NoiseTemplate_GunshipWarning-4]
	_ = x[NoiseTemplate_Footsteps-5]
	_ = x[NoiseTemplate_Weapon_Small-6]
	_ = x[NoiseTemplate_Weapon_Medium-7]
	_ = x[NoiseTemplate_Weapon_Large-8]
	_ = x[NoiseTemplate_Weapon_Huge-9]
	_ = x[NoiseTemplate_Supressor_Small-10]
	_ = x[NoiseTemplate_Supressor_Medium-11]
	_ = x[NoiseTemplate_Supressor_Large-12]
	_ = x[NoiseTemplate_Supressor_Huge-13]
	_ = x[NoiseTemplate_Small_Explosion_Frag-14]
	_ = x[NoiseTemplate_Medium_Explosion_Vehicle-15]
	_ = x[NoiseTemplate_Large_Explosion_Orbital-16]
	_ = x[NoiseTemplate_Huge_Explosion_Hellbomb-17]
	_ = x[NoiseTemplate_BeamHit-18]
	_ = x[NoiseTemplate_ProjectileHit-19]
	_ = x[NoiseTemplate_ProjectileHitSuppressed-20]
	_ = x[NoiseTemplate_Objective_Large_Frequent-21]
	_ = x[NoiseTemplate_Objective_Large_Seldom-22]
	_ = x[NoiseTemplate_Objective_Encounter-23]
	_ = x[NoiseTemplate_Objective_Flag-24]
	_ = x[NoiseTemplate_StratagemBeacon-25]
	_ = x[NoiseTemplate_Extraction-26]
	_ = x[NoiseTemplate_CapitalTower-27]
	_ = x[NoiseTemplate_Value_28_Len_20-28]
	_ = x[NoiseTemplate_Max-29]
}

const _NoiseTemplate_name = "NoiseTemplate_NoneNoiseTemplate_TootNoiseTemplate_EngineNoiseTemplate_EnemyWarningNoiseTemplate_GunshipWarningNoiseTemplate_FootstepsNoiseTemplate_Weapon_SmallNoiseTemplate_Weapon_MediumNoiseTemplate_Weapon_LargeNoiseTemplate_Weapon_HugeNoiseTemplate_Supressor_SmallNoiseTemplate_Supressor_MediumNoiseTemplate_Supressor_LargeNoiseTemplate_Supressor_HugeNoiseTemplate_Small_Explosion_FragNoiseTemplate_Medium_Explosion_VehicleNoiseTemplate_Large_Explosion_OrbitalNoiseTemplate_Huge_Explosion_HellbombNoiseTemplate_BeamHitNoiseTemplate_ProjectileHitNoiseTemplate_ProjectileHitSuppressedNoiseTemplate_Objective_Large_FrequentNoiseTemplate_Objective_Large_SeldomNoiseTemplate_Objective_EncounterNoiseTemplate_Objective_FlagNoiseTemplate_StratagemBeaconNoiseTemplate_ExtractionNoiseTemplate_CapitalTowerNoiseTemplate_Value_28_Len_20NoiseTemplate_Max"

var _NoiseTemplate_index = [...]uint16{0, 18, 36, 56, 82, 110, 133, 159, 186, 212, 237, 266, 296, 325, 353, 387, 425, 462, 499, 520, 547, 584, 622, 658, 691, 719, 748, 772, 798, 827, 844}

func (i NoiseTemplate) String() string {
	if i >= NoiseTemplate(len(_NoiseTemplate_index)-1) {
		return "NoiseTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NoiseTemplate_name[_NoiseTemplate_index[i]:_NoiseTemplate_index[i+1]]
}
