// Code generated by "stringer -type=StatusEffectType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusEffectType_None-0]
	_ = x[StatusEffectType_Blind-1]
	_ = x[StatusEffectType_Bleed-2]
	_ = x[StatusEffectType_Deaf-3]
	_ = x[StatusEffectType_Confusion-4]
	_ = x[StatusEffectType_Fire-5]
	_ = x[StatusEffectType_Value_6_Len_10-6]
	_ = x[StatusEffectType_Slowed-7]
	_ = x[StatusEffectType_Rooted-8]
	_ = x[StatusEffectType_Acid_Splash-9]
	_ = x[StatusEffectType_Acid_Stream-10]
	_ = x[StatusEffectType_Thermite-11]
	_ = x[StatusEffectType_Cyborg_Fire-12]
	_ = x[StatusEffectType_Value_13_Len_6-13]
	_ = x[StatusEffectType_Sand-14]
	_ = x[StatusEffectType_Mud-15]
	_ = x[StatusEffectType_Snow-16]
	_ = x[StatusEffectType_Submerged-17]
	_ = x[StatusEffectType_Thornbush-18]
	_ = x[StatusEffectType_Barbwire-19]
	_ = x[StatusEffectType_BushSmall-20]
	_ = x[StatusEffectType_BushLarge-21]
	_ = x[StatusEffectType_Pure_Damage-22]
	_ = x[StatusEffectType_StimVisual-23]
	_ = x[StatusEffectType_StimStamina-24]
	_ = x[StatusEffectType_StimHeal-25]
	_ = x[StatusEffectType_DownedStimHeal-26]
	_ = x[StatusEffectType_DownedStimVisual-27]
	_ = x[StatusEffectType_StimCooldown-28]
	_ = x[StatusEffectType_BurningHeavy-29]
	_ = x[StatusEffectType_RadiationLight-30]
	_ = x[StatusEffectType_RadiationHeavy-31]
	_ = x[StatusEffectType_Electric-32]
	_ = x[StatusEffectType_Hidden-33]
	_ = x[StatusEffectType_StunSmall-34]
	_ = x[StatusEffectType_StunMedium-35]
	_ = x[StatusEffectType_StunLarge-36]
	_ = x[StatusEffectType_StunMassive-37]
	_ = x[StatusEffectType_StunIlluminate-38]
	_ = x[StatusEffectType_Gas-39]
	_ = x[StatusEffectType_Value_40_Len_9-40]
	_ = x[StatusEffectType_Value_41_Len_13-41]
	_ = x[StatusEffectType_Value_42_Len_19-42]
	_ = x[StatusEffectType_Value_43_Len_19-43]
	_ = x[StatusEffectType_Flashlighted-44]
	_ = x[StatusEffectType_Smoke_Covered-45]
	_ = x[StatusEffectType_BackpackChemicals-46]
	_ = x[StatusEffectType_IntenseHeat-47]
	_ = x[StatusEffectType_ExtremeCold-48]
	_ = x[StatusEffectType_Value_49_Len_6-49]
	_ = x[StatusEffectType_Value_50_Len_9-50]
	_ = x[StatusEffectType_Value_51_Len_9-51]
	_ = x[StatusEffectType_Value_52_Len_9-52]
	_ = x[StatusEffectType_Value_53_Len_8-53]
	_ = x[StatusEffectType_Value_54_Len_9-54]
	_ = x[StatusEffectType_Value_55_Len_9-55]
	_ = x[StatusEffectType_Value_56_Len_9-56]
	_ = x[StatusEffectType_Value_57_Len_10-57]
	_ = x[StatusEffectType_Value_58_Len_17-58]
	_ = x[StatusEffectType_Value_59_Len_19-59]
	_ = x[StatusEffectType_Value_60_Len_19-60]
	_ = x[StatusEffectType_Value_61_Len_19-61]
	_ = x[StatusEffectType_Value_62_Len_12-62]
	_ = x[StatusEffectType_Value_63_Len_28-63]
	_ = x[StatusEffectType_Value_64_Len_19-64]
	_ = x[StatusEffectType_Count-65]
}

const _StatusEffectType_name = "StatusEffectType_NoneStatusEffectType_BlindStatusEffectType_BleedStatusEffectType_DeafStatusEffectType_ConfusionStatusEffectType_FireStatusEffectType_Value_6_Len_10StatusEffectType_SlowedStatusEffectType_RootedStatusEffectType_Acid_SplashStatusEffectType_Acid_StreamStatusEffectType_ThermiteStatusEffectType_Cyborg_FireStatusEffectType_Value_13_Len_6StatusEffectType_SandStatusEffectType_MudStatusEffectType_SnowStatusEffectType_SubmergedStatusEffectType_ThornbushStatusEffectType_BarbwireStatusEffectType_BushSmallStatusEffectType_BushLargeStatusEffectType_Pure_DamageStatusEffectType_StimVisualStatusEffectType_StimStaminaStatusEffectType_StimHealStatusEffectType_DownedStimHealStatusEffectType_DownedStimVisualStatusEffectType_StimCooldownStatusEffectType_BurningHeavyStatusEffectType_RadiationLightStatusEffectType_RadiationHeavyStatusEffectType_ElectricStatusEffectType_HiddenStatusEffectType_StunSmallStatusEffectType_StunMediumStatusEffectType_StunLargeStatusEffectType_StunMassiveStatusEffectType_StunIlluminateStatusEffectType_GasStatusEffectType_Value_40_Len_9StatusEffectType_Value_41_Len_13StatusEffectType_Value_42_Len_19StatusEffectType_Value_43_Len_19StatusEffectType_FlashlightedStatusEffectType_Smoke_CoveredStatusEffectType_BackpackChemicalsStatusEffectType_IntenseHeatStatusEffectType_ExtremeColdStatusEffectType_Value_49_Len_6StatusEffectType_Value_50_Len_9StatusEffectType_Value_51_Len_9StatusEffectType_Value_52_Len_9StatusEffectType_Value_53_Len_8StatusEffectType_Value_54_Len_9StatusEffectType_Value_55_Len_9StatusEffectType_Value_56_Len_9StatusEffectType_Value_57_Len_10StatusEffectType_Value_58_Len_17StatusEffectType_Value_59_Len_19StatusEffectType_Value_60_Len_19StatusEffectType_Value_61_Len_19StatusEffectType_Value_62_Len_12StatusEffectType_Value_63_Len_28StatusEffectType_Value_64_Len_19StatusEffectType_Count"

var _StatusEffectType_index = [...]uint16{0, 21, 43, 65, 86, 112, 133, 164, 187, 210, 238, 266, 291, 319, 350, 371, 391, 412, 438, 464, 489, 515, 541, 569, 596, 624, 649, 680, 713, 742, 771, 802, 833, 858, 881, 907, 934, 960, 988, 1019, 1039, 1070, 1102, 1134, 1166, 1195, 1225, 1259, 1287, 1315, 1346, 1377, 1408, 1439, 1470, 1501, 1532, 1563, 1595, 1627, 1659, 1691, 1723, 1755, 1787, 1819, 1841}

func (i StatusEffectType) String() string {
	if i >= StatusEffectType(len(_StatusEffectType_index)-1) {
		return "StatusEffectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusEffectType_name[_StatusEffectType_index[i]:_StatusEffectType_index[i+1]]
}
