// Code generated by "stringer -type=UnitCustomizationCollectionType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CollectionShuttle-0]
	_ = x[CollectionHellpod-1]
	_ = x[CollectionHellpodRack-2]
	_ = x[CollectionCombatWalker-3]
	_ = x[CollectionCombatWalkerEmancipator-4]
	_ = x[CollectionFRV-5]
	_ = x[CollectionCount-6]
}

const _UnitCustomizationCollectionType_name = "CollectionShuttleCollectionHellpodCollectionHellpodRackCollectionCombatWalkerCollectionCombatWalkerEmancipatorCollectionFRVCollectionCount"

var _UnitCustomizationCollectionType_index = [...]uint8{0, 17, 34, 55, 77, 110, 123, 138}

func (i UnitCustomizationCollectionType) String() string {
	if i >= UnitCustomizationCollectionType(len(_UnitCustomizationCollectionType_index)-1) {
		return "UnitCustomizationCollectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitCustomizationCollectionType_name[_UnitCustomizationCollectionType_index[i]:_UnitCustomizationCollectionType_index[i+1]]
}
