// Code generated by "stringer -type=UnitCustomizationCollectionType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CollectionShuttle-0]
	_ = x[CollectionHellpod-1]
	_ = x[CollectionHellpodRack-2]
	_ = x[CollectionCombatWalker-3]
	_ = x[CollectionCombatWalkerEmancipator-4]
	_ = x[CollectionCombatWalkerLumberer-5]
	_ = x[CollectionCombatWalkerBreacher-6]
	_ = x[CollectionFRV-7]
	_ = x[CollectionFRVFlamer-8]
	_ = x[CollectionFRVSupply-9]
	_ = x[CollectionTank-10]
	_ = x[CollectionCount-11]
}

const _UnitCustomizationCollectionType_name = "CollectionShuttleCollectionHellpodCollectionHellpodRackCollectionCombatWalkerCollectionCombatWalkerEmancipatorCollectionCombatWalkerLumbererCollectionCombatWalkerBreacherCollectionFRVCollectionFRVFlamerCollectionFRVSupplyCollectionTankCollectionCount"

var _UnitCustomizationCollectionType_index = [...]uint8{0, 17, 34, 55, 77, 110, 140, 170, 183, 202, 221, 235, 250}

func (i UnitCustomizationCollectionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UnitCustomizationCollectionType_index)-1 {
		return "UnitCustomizationCollectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitCustomizationCollectionType_name[_UnitCustomizationCollectionType_index[idx]:_UnitCustomizationCollectionType_index[idx+1]]
}
