// Code generated by "stringer -type=UnitCustomizationCollectionCategoryType"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryHangar-0]
	_ = x[CategoryDeliverySystem-1]
	_ = x[CategoryVehicleBay-2]
	_ = x[CategoryCount-3]
}

const _UnitCustomizationCollectionCategoryType_name = "CategoryHangarCategoryDeliverySystemCategoryVehicleBayCategoryCount"

var _UnitCustomizationCollectionCategoryType_index = [...]uint8{0, 14, 36, 54, 67}

func (i UnitCustomizationCollectionCategoryType) String() string {
	if i >= UnitCustomizationCollectionCategoryType(len(_UnitCustomizationCollectionCategoryType_index)-1) {
		return "UnitCustomizationCollectionCategoryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitCustomizationCollectionCategoryType_name[_UnitCustomizationCollectionCategoryType_index[i]:_UnitCustomizationCollectionCategoryType_index[i+1]]
}
