// Code generated by "stringer -type=WeaponCustomizationIKAttach"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponCustomizationIKAttach_None-0]
	_ = x[WeaponCustomizationIKAttach_Optics-1]
	_ = x[WeaponCustomizationIKAttach_Underbarrel-2]
	_ = x[WeaponCustomizationIKAttach_Muzzle-3]
	_ = x[WeaponCustomizationIKAttach_Magazine-4]
	_ = x[WeaponCustomizationIKAttach_Count-5]
}

const _WeaponCustomizationIKAttach_name = "WeaponCustomizationIKAttach_NoneWeaponCustomizationIKAttach_OpticsWeaponCustomizationIKAttach_UnderbarrelWeaponCustomizationIKAttach_MuzzleWeaponCustomizationIKAttach_MagazineWeaponCustomizationIKAttach_Count"

var _WeaponCustomizationIKAttach_index = [...]uint8{0, 32, 66, 105, 139, 175, 208}

func (i WeaponCustomizationIKAttach) String() string {
	if i >= WeaponCustomizationIKAttach(len(_WeaponCustomizationIKAttach_index)-1) {
		return "WeaponCustomizationIKAttach(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponCustomizationIKAttach_name[_WeaponCustomizationIKAttach_index[i]:_WeaponCustomizationIKAttach_index[i+1]]
}
