// Code generated by "stringer -type=WeaponCustomizationUnknownEnum"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponCustomizationUnknownEnum_None-0]
	_ = x[WeaponCustomizationUnknownEnum_Value_1_Len_9-1]
	_ = x[WeaponCustomizationUnknownEnum_Value_2_Len_8-2]
	_ = x[WeaponCustomizationUnknownEnum_Value_3_Len_5-3]
	_ = x[WeaponCustomizationUnknownEnum_Count-4]
}

const _WeaponCustomizationUnknownEnum_name = "WeaponCustomizationUnknownEnum_NoneWeaponCustomizationUnknownEnum_Value_1_Len_9WeaponCustomizationUnknownEnum_Value_2_Len_8WeaponCustomizationUnknownEnum_Value_3_Len_5WeaponCustomizationUnknownEnum_Count"

var _WeaponCustomizationUnknownEnum_index = [...]uint8{0, 35, 79, 123, 167, 203}

func (i WeaponCustomizationUnknownEnum) String() string {
	if i >= WeaponCustomizationUnknownEnum(len(_WeaponCustomizationUnknownEnum_index)-1) {
		return "WeaponCustomizationUnknownEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponCustomizationUnknownEnum_name[_WeaponCustomizationUnknownEnum_index[i]:_WeaponCustomizationUnknownEnum_index[i+1]]
}
