// Code generated by "stringer -type=WeaponCustomizationSortGroups"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeaponCustomizationSortGroups_None-0]
	_ = x[WeaponCustomizationSortGroups_Paint_Default-1]
	_ = x[WeaponCustomizationSortGroups_Paint_Solid-2]
	_ = x[WeaponCustomizationSortGroups_Paint_Camo-3]
	_ = x[WeaponCustomizationSortGroups_Count-4]
}

const _WeaponCustomizationSortGroups_name = "WeaponCustomizationSortGroups_NoneWeaponCustomizationSortGroups_Paint_DefaultWeaponCustomizationSortGroups_Paint_SolidWeaponCustomizationSortGroups_Paint_CamoWeaponCustomizationSortGroups_Count"

var _WeaponCustomizationSortGroups_index = [...]uint8{0, 34, 77, 118, 158, 193}

func (i WeaponCustomizationSortGroups) String() string {
	if i >= WeaponCustomizationSortGroups(len(_WeaponCustomizationSortGroups_index)-1) {
		return "WeaponCustomizationSortGroups(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeaponCustomizationSortGroups_name[_WeaponCustomizationSortGroups_index[i]:_WeaponCustomizationSortGroups_index[i+1]]
}
