// Code generated by "stringer -type=WindEffectTemplate"; DO NOT EDIT.

package datalib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WindEffectTemplate_None-0]
	_ = x[WindEffectTemplate_SmallExplosion-1]
	_ = x[WindEffectTemplate_MediumExplosion-2]
	_ = x[WindEffectTemplate_LargeExplosion-3]
	_ = x[WindEffectTemplate_HugeExplosion-4]
	_ = x[WindEffectTemplate_Hellpod-5]
	_ = x[WindEffectTemplate_BombImpact-6]
	_ = x[WindEffectTemplate_LargeWeaponFire-7]
	_ = x[WindEffectTemplate_LargeWeaponFireLoop-8]
	_ = x[WindEffectTemplate_ImpactMedium-9]
	_ = x[WindEffectTemplate_ImpactHeavy-10]
}

const _WindEffectTemplate_name = "WindEffectTemplate_NoneWindEffectTemplate_SmallExplosionWindEffectTemplate_MediumExplosionWindEffectTemplate_LargeExplosionWindEffectTemplate_HugeExplosionWindEffectTemplate_HellpodWindEffectTemplate_BombImpactWindEffectTemplate_LargeWeaponFireWindEffectTemplate_LargeWeaponFireLoopWindEffectTemplate_ImpactMediumWindEffectTemplate_ImpactHeavy"

var _WindEffectTemplate_index = [...]uint16{0, 23, 56, 90, 123, 155, 181, 210, 244, 282, 313, 343}

func (i WindEffectTemplate) String() string {
	if i >= WindEffectTemplate(len(_WindEffectTemplate_index)-1) {
		return "WindEffectTemplate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindEffectTemplate_name[_WindEffectTemplate_index[i]:_WindEffectTemplate_index[i+1]]
}
