// Code generated by "stringer -type=LevelMetadataType"; DO NOT EDIT.

package level

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelMetadata_NotSeen-0]
	_ = x[LevelMetadata_uint32-1]
	_ = x[LevelMetadata_float32-2]
	_ = x[LevelMetadata_string-3]
}

const _LevelMetadataType_name = "LevelMetadata_NotSeenLevelMetadata_uint32LevelMetadata_float32LevelMetadata_string"

var _LevelMetadataType_index = [...]uint8{0, 21, 41, 62, 82}

func (i LevelMetadataType) String() string {
	if i >= LevelMetadataType(len(_LevelMetadataType_index)-1) {
		return "LevelMetadataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LevelMetadataType_name[_LevelMetadataType_index[i]:_LevelMetadataType_index[i+1]]
}
