// Code generated by "stringer -type=DriverType"; DO NOT EDIT.

package state_machine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriverType_Influence-0]
	_ = x[DriverType_EvalTime-1]
}

const _DriverType_name = "DriverType_InfluenceDriverType_EvalTime"

var _DriverType_index = [...]uint8{0, 20, 39}

func (i DriverType) String() string {
	if i >= DriverType(len(_DriverType_index)-1) {
		return "DriverType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DriverType_name[_DriverType_index[i]:_DriverType_index[i+1]]
}
