// Code generated by "stringer -type=LinkType"; DO NOT EDIT.

package state_machine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LinkType_Immediate-0]
	_ = x[LinkType_WaitEnd-1]
	_ = x[LinkType_SyncBeatClosestImmediate-2]
	_ = x[LinkType_WaitUntilBeat-3]
	_ = x[LinkType_SyncPercentageImmediate-4]
	_ = x[LinkType_SyncInversePercentageImmediate-5]
}

const _LinkType_name = "LinkType_ImmediateLinkType_WaitEndLinkType_SyncBeatClosestImmediateLinkType_WaitUntilBeatLinkType_SyncPercentageImmediateLinkType_SyncInversePercentageImmediate"

var _LinkType_index = [...]uint8{0, 18, 34, 67, 89, 121, 160}

func (i LinkType) String() string {
	if i >= LinkType(len(_LinkType_index)-1) {
		return "LinkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LinkType_name[_LinkType_index[i]:_LinkType_index[i+1]]
}
