// Code generated by "stringer -type=StateType"; DO NOT EDIT.

package state_machine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateType_Clip-0]
	_ = x[StateType_Empty-1]
	_ = x[StateType_CustomBlend-2]
	_ = x[StateType_Blend-3]
}

const _StateType_name = "StateType_ClipStateType_EmptyStateType_CustomBlendStateType_Blend"

var _StateType_index = [...]uint8{0, 14, 29, 50, 65}

func (i StateType) String() string {
	if i >= StateType(len(_StateType_index)-1) {
		return "StateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateType_name[_StateType_index[i]:_StateType_index[i+1]]
}
