// Code generated by "stringer -type=StateType"; DO NOT EDIT.

package state_machine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateType_Clip-0]
	_ = x[StateType_Empty-1]
	_ = x[StateType_Blend-2]
	_ = x[StateType_Time-3]
	_ = x[StateType_Unknown-4]
	_ = x[StateType_Ragdoll-5]
}

const _StateType_name = "StateType_ClipStateType_EmptyStateType_BlendStateType_TimeStateType_UnknownStateType_Ragdoll"

var _StateType_index = [...]uint8{0, 14, 29, 44, 58, 75, 92}

func (i StateType) String() string {
	if i >= StateType(len(_StateType_index)-1) {
		return "StateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateType_name[_StateType_index[i]:_StateType_index[i+1]]
}
