// Code generated by "stringer -type=EntitySettingType"; DO NOT EDIT.

package shading_environment

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SettingType_Scalar-0]
	_ = x[SettingType_CombinedScalars-1]
	_ = x[SettingType_VectorScalar-2]
	_ = x[SettingType_Texture-3]
}

const _EntitySettingType_name = "SettingType_ScalarSettingType_CombinedScalarsSettingType_VectorScalarSettingType_Texture"

var _EntitySettingType_index = [...]uint8{0, 18, 45, 69, 88}

func (i EntitySettingType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EntitySettingType_index)-1 {
		return "EntitySettingType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntitySettingType_name[_EntitySettingType_index[idx]:_EntitySettingType_index[idx+1]]
}
