// Code generated by "stringer -type=VariableContainerType"; DO NOT EDIT.

package shading_environment

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VariableContainerType_Scalar-0]
	_ = x[VariableContainerType_Vec2-1]
	_ = x[VariableContainerType_Vec3-2]
	_ = x[VariableContainerType_Vec4-3]
	_ = x[VariableContainerType_Matrix-4]
	_ = x[VariableContainerType_Unknown1-5]
	_ = x[VariableContainerType_Vec8-6]
	_ = x[VariableContainerType_Unknown2-7]
	_ = x[VariableContainerType_Unknown3-8]
	_ = x[VariableContainerType_Unknown4-9]
	_ = x[VariableContainerType_Hash-10]
}

const _VariableContainerType_name = "VariableContainerType_ScalarVariableContainerType_Vec2VariableContainerType_Vec3VariableContainerType_Vec4VariableContainerType_MatrixVariableContainerType_Unknown1VariableContainerType_Vec8VariableContainerType_Unknown2VariableContainerType_Unknown3VariableContainerType_Unknown4VariableContainerType_Hash"

var _VariableContainerType_index = [...]uint16{0, 28, 54, 80, 106, 134, 164, 190, 220, 250, 280, 306}

func (i VariableContainerType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VariableContainerType_index)-1 {
		return "VariableContainerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariableContainerType_name[_VariableContainerType_index[idx]:_VariableContainerType_index[idx+1]]
}
