// Code generated by "stringer -type=ShaderVariableFlags"; DO NOT EDIT.

package d3dops

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShaderVariableFlags_None-0]
	_ = x[ShaderVariableFlags_UserPacked-1]
	_ = x[ShaderVariableFlags_Used-2]
	_ = x[ShaderVariableFlags_InterfacePointer-4]
	_ = x[ShaderVariableFlags_InterfaceParameter-8]
}

const (
	_ShaderVariableFlags_name_0 = "ShaderVariableFlags_NoneShaderVariableFlags_UserPackedShaderVariableFlags_Used"
	_ShaderVariableFlags_name_1 = "ShaderVariableFlags_InterfacePointer"
	_ShaderVariableFlags_name_2 = "ShaderVariableFlags_InterfaceParameter"
)

var (
	_ShaderVariableFlags_index_0 = [...]uint8{0, 24, 54, 78}
)

func (i ShaderVariableFlags) String() string {
	switch {
	case i <= 2:
		return _ShaderVariableFlags_name_0[_ShaderVariableFlags_index_0[i]:_ShaderVariableFlags_index_0[i+1]]
	case i == 4:
		return _ShaderVariableFlags_name_1
	case i == 8:
		return _ShaderVariableFlags_name_2
	default:
		return "ShaderVariableFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
